// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BasicDataType.proto

package org.jcjxb.wsn.service.proto;

public final class BasicDataType {
  private BasicDataType() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PositionOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional double x = 1;
    boolean hasX();
    double getX();
    
    // optional double y = 2;
    boolean hasY();
    double getY();
  }
  public static final class Position extends
      com.google.protobuf.GeneratedMessage
      implements PositionOrBuilder {
    // Use Position.newBuilder() to construct.
    private Position(Builder builder) {
      super(builder);
    }
    private Position(boolean noInit) {}
    
    private static final Position defaultInstance;
    public static Position getDefaultInstance() {
      return defaultInstance;
    }
    
    public Position getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.jcjxb.wsn.service.proto.BasicDataType.internal_static_org_jcjxb_wsn_service_Position_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.jcjxb.wsn.service.proto.BasicDataType.internal_static_org_jcjxb_wsn_service_Position_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional double x = 1;
    public static final int X_FIELD_NUMBER = 1;
    private double x_;
    public boolean hasX() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public double getX() {
      return x_;
    }
    
    // optional double y = 2;
    public static final int Y_FIELD_NUMBER = 2;
    private double y_;
    public boolean hasY() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public double getY() {
      return y_;
    }
    
    private void initFields() {
      x_ = 0D;
      y_ = 0D;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeDouble(1, x_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeDouble(2, y_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, x_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, y_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.jcjxb.wsn.service.proto.BasicDataType.Position parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.jcjxb.wsn.service.proto.BasicDataType.Position parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.jcjxb.wsn.service.proto.BasicDataType.Position parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.jcjxb.wsn.service.proto.BasicDataType.Position parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.jcjxb.wsn.service.proto.BasicDataType.Position parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.jcjxb.wsn.service.proto.BasicDataType.Position parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.jcjxb.wsn.service.proto.BasicDataType.Position parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.jcjxb.wsn.service.proto.BasicDataType.Position parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.jcjxb.wsn.service.proto.BasicDataType.Position parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.jcjxb.wsn.service.proto.BasicDataType.Position parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.jcjxb.wsn.service.proto.BasicDataType.Position prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.jcjxb.wsn.service.proto.BasicDataType.PositionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.jcjxb.wsn.service.proto.BasicDataType.internal_static_org_jcjxb_wsn_service_Position_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.jcjxb.wsn.service.proto.BasicDataType.internal_static_org_jcjxb_wsn_service_Position_fieldAccessorTable;
      }
      
      // Construct using org.jcjxb.wsn.service.proto.BasicDataType.Position.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        x_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000001);
        y_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.jcjxb.wsn.service.proto.BasicDataType.Position.getDescriptor();
      }
      
      public org.jcjxb.wsn.service.proto.BasicDataType.Position getDefaultInstanceForType() {
        return org.jcjxb.wsn.service.proto.BasicDataType.Position.getDefaultInstance();
      }
      
      public org.jcjxb.wsn.service.proto.BasicDataType.Position build() {
        org.jcjxb.wsn.service.proto.BasicDataType.Position result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.jcjxb.wsn.service.proto.BasicDataType.Position buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.jcjxb.wsn.service.proto.BasicDataType.Position result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.jcjxb.wsn.service.proto.BasicDataType.Position buildPartial() {
        org.jcjxb.wsn.service.proto.BasicDataType.Position result = new org.jcjxb.wsn.service.proto.BasicDataType.Position(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.x_ = x_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.y_ = y_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.jcjxb.wsn.service.proto.BasicDataType.Position) {
          return mergeFrom((org.jcjxb.wsn.service.proto.BasicDataType.Position)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.jcjxb.wsn.service.proto.BasicDataType.Position other) {
        if (other == org.jcjxb.wsn.service.proto.BasicDataType.Position.getDefaultInstance()) return this;
        if (other.hasX()) {
          setX(other.getX());
        }
        if (other.hasY()) {
          setY(other.getY());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 9: {
              bitField0_ |= 0x00000001;
              x_ = input.readDouble();
              break;
            }
            case 17: {
              bitField0_ |= 0x00000002;
              y_ = input.readDouble();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional double x = 1;
      private double x_ ;
      public boolean hasX() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public double getX() {
        return x_;
      }
      public Builder setX(double value) {
        bitField0_ |= 0x00000001;
        x_ = value;
        onChanged();
        return this;
      }
      public Builder clearX() {
        bitField0_ = (bitField0_ & ~0x00000001);
        x_ = 0D;
        onChanged();
        return this;
      }
      
      // optional double y = 2;
      private double y_ ;
      public boolean hasY() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public double getY() {
        return y_;
      }
      public Builder setY(double value) {
        bitField0_ |= 0x00000002;
        y_ = value;
        onChanged();
        return this;
      }
      public Builder clearY() {
        bitField0_ = (bitField0_ & ~0x00000002);
        y_ = 0D;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:org.jcjxb.wsn.service.Position)
    }
    
    static {
      defaultInstance = new Position(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:org.jcjxb.wsn.service.Position)
  }
  
  public interface PositionListOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated .org.jcjxb.wsn.service.Position postion = 1;
    java.util.List<org.jcjxb.wsn.service.proto.BasicDataType.Position> 
        getPostionList();
    org.jcjxb.wsn.service.proto.BasicDataType.Position getPostion(int index);
    int getPostionCount();
    java.util.List<? extends org.jcjxb.wsn.service.proto.BasicDataType.PositionOrBuilder> 
        getPostionOrBuilderList();
    org.jcjxb.wsn.service.proto.BasicDataType.PositionOrBuilder getPostionOrBuilder(
        int index);
  }
  public static final class PositionList extends
      com.google.protobuf.GeneratedMessage
      implements PositionListOrBuilder {
    // Use PositionList.newBuilder() to construct.
    private PositionList(Builder builder) {
      super(builder);
    }
    private PositionList(boolean noInit) {}
    
    private static final PositionList defaultInstance;
    public static PositionList getDefaultInstance() {
      return defaultInstance;
    }
    
    public PositionList getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.jcjxb.wsn.service.proto.BasicDataType.internal_static_org_jcjxb_wsn_service_PositionList_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.jcjxb.wsn.service.proto.BasicDataType.internal_static_org_jcjxb_wsn_service_PositionList_fieldAccessorTable;
    }
    
    // repeated .org.jcjxb.wsn.service.Position postion = 1;
    public static final int POSTION_FIELD_NUMBER = 1;
    private java.util.List<org.jcjxb.wsn.service.proto.BasicDataType.Position> postion_;
    public java.util.List<org.jcjxb.wsn.service.proto.BasicDataType.Position> getPostionList() {
      return postion_;
    }
    public java.util.List<? extends org.jcjxb.wsn.service.proto.BasicDataType.PositionOrBuilder> 
        getPostionOrBuilderList() {
      return postion_;
    }
    public int getPostionCount() {
      return postion_.size();
    }
    public org.jcjxb.wsn.service.proto.BasicDataType.Position getPostion(int index) {
      return postion_.get(index);
    }
    public org.jcjxb.wsn.service.proto.BasicDataType.PositionOrBuilder getPostionOrBuilder(
        int index) {
      return postion_.get(index);
    }
    
    private void initFields() {
      postion_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < postion_.size(); i++) {
        output.writeMessage(1, postion_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (int i = 0; i < postion_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, postion_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.jcjxb.wsn.service.proto.BasicDataType.PositionList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.jcjxb.wsn.service.proto.BasicDataType.PositionList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.jcjxb.wsn.service.proto.BasicDataType.PositionList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.jcjxb.wsn.service.proto.BasicDataType.PositionList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.jcjxb.wsn.service.proto.BasicDataType.PositionList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.jcjxb.wsn.service.proto.BasicDataType.PositionList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.jcjxb.wsn.service.proto.BasicDataType.PositionList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.jcjxb.wsn.service.proto.BasicDataType.PositionList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.jcjxb.wsn.service.proto.BasicDataType.PositionList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.jcjxb.wsn.service.proto.BasicDataType.PositionList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.jcjxb.wsn.service.proto.BasicDataType.PositionList prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.jcjxb.wsn.service.proto.BasicDataType.PositionListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.jcjxb.wsn.service.proto.BasicDataType.internal_static_org_jcjxb_wsn_service_PositionList_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.jcjxb.wsn.service.proto.BasicDataType.internal_static_org_jcjxb_wsn_service_PositionList_fieldAccessorTable;
      }
      
      // Construct using org.jcjxb.wsn.service.proto.BasicDataType.PositionList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getPostionFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (postionBuilder_ == null) {
          postion_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          postionBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.jcjxb.wsn.service.proto.BasicDataType.PositionList.getDescriptor();
      }
      
      public org.jcjxb.wsn.service.proto.BasicDataType.PositionList getDefaultInstanceForType() {
        return org.jcjxb.wsn.service.proto.BasicDataType.PositionList.getDefaultInstance();
      }
      
      public org.jcjxb.wsn.service.proto.BasicDataType.PositionList build() {
        org.jcjxb.wsn.service.proto.BasicDataType.PositionList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.jcjxb.wsn.service.proto.BasicDataType.PositionList buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.jcjxb.wsn.service.proto.BasicDataType.PositionList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.jcjxb.wsn.service.proto.BasicDataType.PositionList buildPartial() {
        org.jcjxb.wsn.service.proto.BasicDataType.PositionList result = new org.jcjxb.wsn.service.proto.BasicDataType.PositionList(this);
        int from_bitField0_ = bitField0_;
        if (postionBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            postion_ = java.util.Collections.unmodifiableList(postion_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.postion_ = postion_;
        } else {
          result.postion_ = postionBuilder_.build();
        }
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.jcjxb.wsn.service.proto.BasicDataType.PositionList) {
          return mergeFrom((org.jcjxb.wsn.service.proto.BasicDataType.PositionList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.jcjxb.wsn.service.proto.BasicDataType.PositionList other) {
        if (other == org.jcjxb.wsn.service.proto.BasicDataType.PositionList.getDefaultInstance()) return this;
        if (postionBuilder_ == null) {
          if (!other.postion_.isEmpty()) {
            if (postion_.isEmpty()) {
              postion_ = other.postion_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensurePostionIsMutable();
              postion_.addAll(other.postion_);
            }
            onChanged();
          }
        } else {
          if (!other.postion_.isEmpty()) {
            if (postionBuilder_.isEmpty()) {
              postionBuilder_.dispose();
              postionBuilder_ = null;
              postion_ = other.postion_;
              bitField0_ = (bitField0_ & ~0x00000001);
              postionBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getPostionFieldBuilder() : null;
            } else {
              postionBuilder_.addAllMessages(other.postion_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              org.jcjxb.wsn.service.proto.BasicDataType.Position.Builder subBuilder = org.jcjxb.wsn.service.proto.BasicDataType.Position.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addPostion(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated .org.jcjxb.wsn.service.Position postion = 1;
      private java.util.List<org.jcjxb.wsn.service.proto.BasicDataType.Position> postion_ =
        java.util.Collections.emptyList();
      private void ensurePostionIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          postion_ = new java.util.ArrayList<org.jcjxb.wsn.service.proto.BasicDataType.Position>(postion_);
          bitField0_ |= 0x00000001;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          org.jcjxb.wsn.service.proto.BasicDataType.Position, org.jcjxb.wsn.service.proto.BasicDataType.Position.Builder, org.jcjxb.wsn.service.proto.BasicDataType.PositionOrBuilder> postionBuilder_;
      
      public java.util.List<org.jcjxb.wsn.service.proto.BasicDataType.Position> getPostionList() {
        if (postionBuilder_ == null) {
          return java.util.Collections.unmodifiableList(postion_);
        } else {
          return postionBuilder_.getMessageList();
        }
      }
      public int getPostionCount() {
        if (postionBuilder_ == null) {
          return postion_.size();
        } else {
          return postionBuilder_.getCount();
        }
      }
      public org.jcjxb.wsn.service.proto.BasicDataType.Position getPostion(int index) {
        if (postionBuilder_ == null) {
          return postion_.get(index);
        } else {
          return postionBuilder_.getMessage(index);
        }
      }
      public Builder setPostion(
          int index, org.jcjxb.wsn.service.proto.BasicDataType.Position value) {
        if (postionBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePostionIsMutable();
          postion_.set(index, value);
          onChanged();
        } else {
          postionBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setPostion(
          int index, org.jcjxb.wsn.service.proto.BasicDataType.Position.Builder builderForValue) {
        if (postionBuilder_ == null) {
          ensurePostionIsMutable();
          postion_.set(index, builderForValue.build());
          onChanged();
        } else {
          postionBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addPostion(org.jcjxb.wsn.service.proto.BasicDataType.Position value) {
        if (postionBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePostionIsMutable();
          postion_.add(value);
          onChanged();
        } else {
          postionBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addPostion(
          int index, org.jcjxb.wsn.service.proto.BasicDataType.Position value) {
        if (postionBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePostionIsMutable();
          postion_.add(index, value);
          onChanged();
        } else {
          postionBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addPostion(
          org.jcjxb.wsn.service.proto.BasicDataType.Position.Builder builderForValue) {
        if (postionBuilder_ == null) {
          ensurePostionIsMutable();
          postion_.add(builderForValue.build());
          onChanged();
        } else {
          postionBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addPostion(
          int index, org.jcjxb.wsn.service.proto.BasicDataType.Position.Builder builderForValue) {
        if (postionBuilder_ == null) {
          ensurePostionIsMutable();
          postion_.add(index, builderForValue.build());
          onChanged();
        } else {
          postionBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllPostion(
          java.lang.Iterable<? extends org.jcjxb.wsn.service.proto.BasicDataType.Position> values) {
        if (postionBuilder_ == null) {
          ensurePostionIsMutable();
          super.addAll(values, postion_);
          onChanged();
        } else {
          postionBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearPostion() {
        if (postionBuilder_ == null) {
          postion_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          postionBuilder_.clear();
        }
        return this;
      }
      public Builder removePostion(int index) {
        if (postionBuilder_ == null) {
          ensurePostionIsMutable();
          postion_.remove(index);
          onChanged();
        } else {
          postionBuilder_.remove(index);
        }
        return this;
      }
      public org.jcjxb.wsn.service.proto.BasicDataType.Position.Builder getPostionBuilder(
          int index) {
        return getPostionFieldBuilder().getBuilder(index);
      }
      public org.jcjxb.wsn.service.proto.BasicDataType.PositionOrBuilder getPostionOrBuilder(
          int index) {
        if (postionBuilder_ == null) {
          return postion_.get(index);  } else {
          return postionBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends org.jcjxb.wsn.service.proto.BasicDataType.PositionOrBuilder> 
           getPostionOrBuilderList() {
        if (postionBuilder_ != null) {
          return postionBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(postion_);
        }
      }
      public org.jcjxb.wsn.service.proto.BasicDataType.Position.Builder addPostionBuilder() {
        return getPostionFieldBuilder().addBuilder(
            org.jcjxb.wsn.service.proto.BasicDataType.Position.getDefaultInstance());
      }
      public org.jcjxb.wsn.service.proto.BasicDataType.Position.Builder addPostionBuilder(
          int index) {
        return getPostionFieldBuilder().addBuilder(
            index, org.jcjxb.wsn.service.proto.BasicDataType.Position.getDefaultInstance());
      }
      public java.util.List<org.jcjxb.wsn.service.proto.BasicDataType.Position.Builder> 
           getPostionBuilderList() {
        return getPostionFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          org.jcjxb.wsn.service.proto.BasicDataType.Position, org.jcjxb.wsn.service.proto.BasicDataType.Position.Builder, org.jcjxb.wsn.service.proto.BasicDataType.PositionOrBuilder> 
          getPostionFieldBuilder() {
        if (postionBuilder_ == null) {
          postionBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              org.jcjxb.wsn.service.proto.BasicDataType.Position, org.jcjxb.wsn.service.proto.BasicDataType.Position.Builder, org.jcjxb.wsn.service.proto.BasicDataType.PositionOrBuilder>(
                  postion_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          postion_ = null;
        }
        return postionBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:org.jcjxb.wsn.service.PositionList)
    }
    
    static {
      defaultInstance = new PositionList(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:org.jcjxb.wsn.service.PositionList)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_jcjxb_wsn_service_Position_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_jcjxb_wsn_service_Position_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_jcjxb_wsn_service_PositionList_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_jcjxb_wsn_service_PositionList_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023BasicDataType.proto\022\025org.jcjxb.wsn.ser" +
      "vice\" \n\010Position\022\t\n\001x\030\001 \001(\001\022\t\n\001y\030\002 \001(\001\"@" +
      "\n\014PositionList\0220\n\007postion\030\001 \003(\0132\037.org.jc" +
      "jxb.wsn.service.PositionB,\n\033org.jcjxb.ws" +
      "n.service.protoB\rBasicDataType"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_org_jcjxb_wsn_service_Position_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_org_jcjxb_wsn_service_Position_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_jcjxb_wsn_service_Position_descriptor,
              new java.lang.String[] { "X", "Y", },
              org.jcjxb.wsn.service.proto.BasicDataType.Position.class,
              org.jcjxb.wsn.service.proto.BasicDataType.Position.Builder.class);
          internal_static_org_jcjxb_wsn_service_PositionList_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_org_jcjxb_wsn_service_PositionList_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_jcjxb_wsn_service_PositionList_descriptor,
              new java.lang.String[] { "Postion", },
              org.jcjxb.wsn.service.proto.BasicDataType.PositionList.class,
              org.jcjxb.wsn.service.proto.BasicDataType.PositionList.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
