// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DataType.proto

package org.jcjxb.wsn.service.proto;

public final class DataType {
  private DataType() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public enum DeployType
      implements com.google.protobuf.ProtocolMessageEnum {
    RANDOM(0, 0),
    STATIC(1, 1),
    GRID(2, 2),
    CIRCLE(3, 3),
    ;
    
    public static final int RANDOM_VALUE = 0;
    public static final int STATIC_VALUE = 1;
    public static final int GRID_VALUE = 2;
    public static final int CIRCLE_VALUE = 3;
    
    
    public final int getNumber() { return value; }
    
    public static DeployType valueOf(int value) {
      switch (value) {
        case 0: return RANDOM;
        case 1: return STATIC;
        case 2: return GRID;
        case 3: return CIRCLE;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<DeployType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<DeployType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<DeployType>() {
            public DeployType findValueByNumber(int number) {
              return DeployType.valueOf(number);
            }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return org.jcjxb.wsn.service.proto.DataType.getDescriptor().getEnumTypes().get(0);
    }
    
    private static final DeployType[] VALUES = {
      RANDOM, STATIC, GRID, CIRCLE, 
    };
    
    public static DeployType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    
    private final int index;
    private final int value;
    
    private DeployType(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    // @@protoc_insertion_point(enum_scope:org.jcjxb.wsn.service.DeployType)
  }
  
  public interface PositionOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional double x = 1;
    boolean hasX();
    double getX();
    
    // optional double y = 2;
    boolean hasY();
    double getY();
    
    // optional double z = 3;
    boolean hasZ();
    double getZ();
  }
  public static final class Position extends
      com.google.protobuf.GeneratedMessage
      implements PositionOrBuilder {
    // Use Position.newBuilder() to construct.
    private Position(Builder builder) {
      super(builder);
    }
    private Position(boolean noInit) {}
    
    private static final Position defaultInstance;
    public static Position getDefaultInstance() {
      return defaultInstance;
    }
    
    public Position getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.jcjxb.wsn.service.proto.DataType.internal_static_org_jcjxb_wsn_service_Position_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.jcjxb.wsn.service.proto.DataType.internal_static_org_jcjxb_wsn_service_Position_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional double x = 1;
    public static final int X_FIELD_NUMBER = 1;
    private double x_;
    public boolean hasX() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public double getX() {
      return x_;
    }
    
    // optional double y = 2;
    public static final int Y_FIELD_NUMBER = 2;
    private double y_;
    public boolean hasY() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public double getY() {
      return y_;
    }
    
    // optional double z = 3;
    public static final int Z_FIELD_NUMBER = 3;
    private double z_;
    public boolean hasZ() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public double getZ() {
      return z_;
    }
    
    private void initFields() {
      x_ = 0D;
      y_ = 0D;
      z_ = 0D;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeDouble(1, x_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeDouble(2, y_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeDouble(3, z_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, x_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, y_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, z_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.jcjxb.wsn.service.proto.DataType.Position parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.jcjxb.wsn.service.proto.DataType.Position parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.jcjxb.wsn.service.proto.DataType.Position parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.jcjxb.wsn.service.proto.DataType.Position parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.jcjxb.wsn.service.proto.DataType.Position parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.jcjxb.wsn.service.proto.DataType.Position parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.jcjxb.wsn.service.proto.DataType.Position parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.jcjxb.wsn.service.proto.DataType.Position parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.jcjxb.wsn.service.proto.DataType.Position parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.jcjxb.wsn.service.proto.DataType.Position parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.jcjxb.wsn.service.proto.DataType.Position prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.jcjxb.wsn.service.proto.DataType.PositionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.jcjxb.wsn.service.proto.DataType.internal_static_org_jcjxb_wsn_service_Position_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.jcjxb.wsn.service.proto.DataType.internal_static_org_jcjxb_wsn_service_Position_fieldAccessorTable;
      }
      
      // Construct using org.jcjxb.wsn.service.proto.DataType.Position.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        x_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000001);
        y_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000002);
        z_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.jcjxb.wsn.service.proto.DataType.Position.getDescriptor();
      }
      
      public org.jcjxb.wsn.service.proto.DataType.Position getDefaultInstanceForType() {
        return org.jcjxb.wsn.service.proto.DataType.Position.getDefaultInstance();
      }
      
      public org.jcjxb.wsn.service.proto.DataType.Position build() {
        org.jcjxb.wsn.service.proto.DataType.Position result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.jcjxb.wsn.service.proto.DataType.Position buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.jcjxb.wsn.service.proto.DataType.Position result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.jcjxb.wsn.service.proto.DataType.Position buildPartial() {
        org.jcjxb.wsn.service.proto.DataType.Position result = new org.jcjxb.wsn.service.proto.DataType.Position(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.x_ = x_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.y_ = y_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.z_ = z_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.jcjxb.wsn.service.proto.DataType.Position) {
          return mergeFrom((org.jcjxb.wsn.service.proto.DataType.Position)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.jcjxb.wsn.service.proto.DataType.Position other) {
        if (other == org.jcjxb.wsn.service.proto.DataType.Position.getDefaultInstance()) return this;
        if (other.hasX()) {
          setX(other.getX());
        }
        if (other.hasY()) {
          setY(other.getY());
        }
        if (other.hasZ()) {
          setZ(other.getZ());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 9: {
              bitField0_ |= 0x00000001;
              x_ = input.readDouble();
              break;
            }
            case 17: {
              bitField0_ |= 0x00000002;
              y_ = input.readDouble();
              break;
            }
            case 25: {
              bitField0_ |= 0x00000004;
              z_ = input.readDouble();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional double x = 1;
      private double x_ ;
      public boolean hasX() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public double getX() {
        return x_;
      }
      public Builder setX(double value) {
        bitField0_ |= 0x00000001;
        x_ = value;
        onChanged();
        return this;
      }
      public Builder clearX() {
        bitField0_ = (bitField0_ & ~0x00000001);
        x_ = 0D;
        onChanged();
        return this;
      }
      
      // optional double y = 2;
      private double y_ ;
      public boolean hasY() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public double getY() {
        return y_;
      }
      public Builder setY(double value) {
        bitField0_ |= 0x00000002;
        y_ = value;
        onChanged();
        return this;
      }
      public Builder clearY() {
        bitField0_ = (bitField0_ & ~0x00000002);
        y_ = 0D;
        onChanged();
        return this;
      }
      
      // optional double z = 3;
      private double z_ ;
      public boolean hasZ() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public double getZ() {
        return z_;
      }
      public Builder setZ(double value) {
        bitField0_ |= 0x00000004;
        z_ = value;
        onChanged();
        return this;
      }
      public Builder clearZ() {
        bitField0_ = (bitField0_ & ~0x00000004);
        z_ = 0D;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:org.jcjxb.wsn.service.Position)
    }
    
    static {
      defaultInstance = new Position(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:org.jcjxb.wsn.service.Position)
  }
  
  public interface PositionListOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional .org.jcjxb.wsn.service.DeployType deployType = 1;
    boolean hasDeployType();
    org.jcjxb.wsn.service.proto.DataType.DeployType getDeployType();
    
    // repeated .org.jcjxb.wsn.service.Position postions = 2;
    java.util.List<org.jcjxb.wsn.service.proto.DataType.Position> 
        getPostionsList();
    org.jcjxb.wsn.service.proto.DataType.Position getPostions(int index);
    int getPostionsCount();
    java.util.List<? extends org.jcjxb.wsn.service.proto.DataType.PositionOrBuilder> 
        getPostionsOrBuilderList();
    org.jcjxb.wsn.service.proto.DataType.PositionOrBuilder getPostionsOrBuilder(
        int index);
  }
  public static final class PositionList extends
      com.google.protobuf.GeneratedMessage
      implements PositionListOrBuilder {
    // Use PositionList.newBuilder() to construct.
    private PositionList(Builder builder) {
      super(builder);
    }
    private PositionList(boolean noInit) {}
    
    private static final PositionList defaultInstance;
    public static PositionList getDefaultInstance() {
      return defaultInstance;
    }
    
    public PositionList getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.jcjxb.wsn.service.proto.DataType.internal_static_org_jcjxb_wsn_service_PositionList_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.jcjxb.wsn.service.proto.DataType.internal_static_org_jcjxb_wsn_service_PositionList_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional .org.jcjxb.wsn.service.DeployType deployType = 1;
    public static final int DEPLOYTYPE_FIELD_NUMBER = 1;
    private org.jcjxb.wsn.service.proto.DataType.DeployType deployType_;
    public boolean hasDeployType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public org.jcjxb.wsn.service.proto.DataType.DeployType getDeployType() {
      return deployType_;
    }
    
    // repeated .org.jcjxb.wsn.service.Position postions = 2;
    public static final int POSTIONS_FIELD_NUMBER = 2;
    private java.util.List<org.jcjxb.wsn.service.proto.DataType.Position> postions_;
    public java.util.List<org.jcjxb.wsn.service.proto.DataType.Position> getPostionsList() {
      return postions_;
    }
    public java.util.List<? extends org.jcjxb.wsn.service.proto.DataType.PositionOrBuilder> 
        getPostionsOrBuilderList() {
      return postions_;
    }
    public int getPostionsCount() {
      return postions_.size();
    }
    public org.jcjxb.wsn.service.proto.DataType.Position getPostions(int index) {
      return postions_.get(index);
    }
    public org.jcjxb.wsn.service.proto.DataType.PositionOrBuilder getPostionsOrBuilder(
        int index) {
      return postions_.get(index);
    }
    
    private void initFields() {
      deployType_ = org.jcjxb.wsn.service.proto.DataType.DeployType.RANDOM;
      postions_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, deployType_.getNumber());
      }
      for (int i = 0; i < postions_.size(); i++) {
        output.writeMessage(2, postions_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, deployType_.getNumber());
      }
      for (int i = 0; i < postions_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, postions_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.jcjxb.wsn.service.proto.DataType.PositionList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.jcjxb.wsn.service.proto.DataType.PositionList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.jcjxb.wsn.service.proto.DataType.PositionList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.jcjxb.wsn.service.proto.DataType.PositionList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.jcjxb.wsn.service.proto.DataType.PositionList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.jcjxb.wsn.service.proto.DataType.PositionList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.jcjxb.wsn.service.proto.DataType.PositionList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.jcjxb.wsn.service.proto.DataType.PositionList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.jcjxb.wsn.service.proto.DataType.PositionList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.jcjxb.wsn.service.proto.DataType.PositionList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.jcjxb.wsn.service.proto.DataType.PositionList prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.jcjxb.wsn.service.proto.DataType.PositionListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.jcjxb.wsn.service.proto.DataType.internal_static_org_jcjxb_wsn_service_PositionList_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.jcjxb.wsn.service.proto.DataType.internal_static_org_jcjxb_wsn_service_PositionList_fieldAccessorTable;
      }
      
      // Construct using org.jcjxb.wsn.service.proto.DataType.PositionList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getPostionsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        deployType_ = org.jcjxb.wsn.service.proto.DataType.DeployType.RANDOM;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (postionsBuilder_ == null) {
          postions_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          postionsBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.jcjxb.wsn.service.proto.DataType.PositionList.getDescriptor();
      }
      
      public org.jcjxb.wsn.service.proto.DataType.PositionList getDefaultInstanceForType() {
        return org.jcjxb.wsn.service.proto.DataType.PositionList.getDefaultInstance();
      }
      
      public org.jcjxb.wsn.service.proto.DataType.PositionList build() {
        org.jcjxb.wsn.service.proto.DataType.PositionList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.jcjxb.wsn.service.proto.DataType.PositionList buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.jcjxb.wsn.service.proto.DataType.PositionList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.jcjxb.wsn.service.proto.DataType.PositionList buildPartial() {
        org.jcjxb.wsn.service.proto.DataType.PositionList result = new org.jcjxb.wsn.service.proto.DataType.PositionList(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.deployType_ = deployType_;
        if (postionsBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            postions_ = java.util.Collections.unmodifiableList(postions_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.postions_ = postions_;
        } else {
          result.postions_ = postionsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.jcjxb.wsn.service.proto.DataType.PositionList) {
          return mergeFrom((org.jcjxb.wsn.service.proto.DataType.PositionList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.jcjxb.wsn.service.proto.DataType.PositionList other) {
        if (other == org.jcjxb.wsn.service.proto.DataType.PositionList.getDefaultInstance()) return this;
        if (other.hasDeployType()) {
          setDeployType(other.getDeployType());
        }
        if (postionsBuilder_ == null) {
          if (!other.postions_.isEmpty()) {
            if (postions_.isEmpty()) {
              postions_ = other.postions_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensurePostionsIsMutable();
              postions_.addAll(other.postions_);
            }
            onChanged();
          }
        } else {
          if (!other.postions_.isEmpty()) {
            if (postionsBuilder_.isEmpty()) {
              postionsBuilder_.dispose();
              postionsBuilder_ = null;
              postions_ = other.postions_;
              bitField0_ = (bitField0_ & ~0x00000002);
              postionsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getPostionsFieldBuilder() : null;
            } else {
              postionsBuilder_.addAllMessages(other.postions_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              org.jcjxb.wsn.service.proto.DataType.DeployType value = org.jcjxb.wsn.service.proto.DataType.DeployType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                deployType_ = value;
              }
              break;
            }
            case 18: {
              org.jcjxb.wsn.service.proto.DataType.Position.Builder subBuilder = org.jcjxb.wsn.service.proto.DataType.Position.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addPostions(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional .org.jcjxb.wsn.service.DeployType deployType = 1;
      private org.jcjxb.wsn.service.proto.DataType.DeployType deployType_ = org.jcjxb.wsn.service.proto.DataType.DeployType.RANDOM;
      public boolean hasDeployType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public org.jcjxb.wsn.service.proto.DataType.DeployType getDeployType() {
        return deployType_;
      }
      public Builder setDeployType(org.jcjxb.wsn.service.proto.DataType.DeployType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        deployType_ = value;
        onChanged();
        return this;
      }
      public Builder clearDeployType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        deployType_ = org.jcjxb.wsn.service.proto.DataType.DeployType.RANDOM;
        onChanged();
        return this;
      }
      
      // repeated .org.jcjxb.wsn.service.Position postions = 2;
      private java.util.List<org.jcjxb.wsn.service.proto.DataType.Position> postions_ =
        java.util.Collections.emptyList();
      private void ensurePostionsIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          postions_ = new java.util.ArrayList<org.jcjxb.wsn.service.proto.DataType.Position>(postions_);
          bitField0_ |= 0x00000002;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          org.jcjxb.wsn.service.proto.DataType.Position, org.jcjxb.wsn.service.proto.DataType.Position.Builder, org.jcjxb.wsn.service.proto.DataType.PositionOrBuilder> postionsBuilder_;
      
      public java.util.List<org.jcjxb.wsn.service.proto.DataType.Position> getPostionsList() {
        if (postionsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(postions_);
        } else {
          return postionsBuilder_.getMessageList();
        }
      }
      public int getPostionsCount() {
        if (postionsBuilder_ == null) {
          return postions_.size();
        } else {
          return postionsBuilder_.getCount();
        }
      }
      public org.jcjxb.wsn.service.proto.DataType.Position getPostions(int index) {
        if (postionsBuilder_ == null) {
          return postions_.get(index);
        } else {
          return postionsBuilder_.getMessage(index);
        }
      }
      public Builder setPostions(
          int index, org.jcjxb.wsn.service.proto.DataType.Position value) {
        if (postionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePostionsIsMutable();
          postions_.set(index, value);
          onChanged();
        } else {
          postionsBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setPostions(
          int index, org.jcjxb.wsn.service.proto.DataType.Position.Builder builderForValue) {
        if (postionsBuilder_ == null) {
          ensurePostionsIsMutable();
          postions_.set(index, builderForValue.build());
          onChanged();
        } else {
          postionsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addPostions(org.jcjxb.wsn.service.proto.DataType.Position value) {
        if (postionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePostionsIsMutable();
          postions_.add(value);
          onChanged();
        } else {
          postionsBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addPostions(
          int index, org.jcjxb.wsn.service.proto.DataType.Position value) {
        if (postionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePostionsIsMutable();
          postions_.add(index, value);
          onChanged();
        } else {
          postionsBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addPostions(
          org.jcjxb.wsn.service.proto.DataType.Position.Builder builderForValue) {
        if (postionsBuilder_ == null) {
          ensurePostionsIsMutable();
          postions_.add(builderForValue.build());
          onChanged();
        } else {
          postionsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addPostions(
          int index, org.jcjxb.wsn.service.proto.DataType.Position.Builder builderForValue) {
        if (postionsBuilder_ == null) {
          ensurePostionsIsMutable();
          postions_.add(index, builderForValue.build());
          onChanged();
        } else {
          postionsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllPostions(
          java.lang.Iterable<? extends org.jcjxb.wsn.service.proto.DataType.Position> values) {
        if (postionsBuilder_ == null) {
          ensurePostionsIsMutable();
          super.addAll(values, postions_);
          onChanged();
        } else {
          postionsBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearPostions() {
        if (postionsBuilder_ == null) {
          postions_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          postionsBuilder_.clear();
        }
        return this;
      }
      public Builder removePostions(int index) {
        if (postionsBuilder_ == null) {
          ensurePostionsIsMutable();
          postions_.remove(index);
          onChanged();
        } else {
          postionsBuilder_.remove(index);
        }
        return this;
      }
      public org.jcjxb.wsn.service.proto.DataType.Position.Builder getPostionsBuilder(
          int index) {
        return getPostionsFieldBuilder().getBuilder(index);
      }
      public org.jcjxb.wsn.service.proto.DataType.PositionOrBuilder getPostionsOrBuilder(
          int index) {
        if (postionsBuilder_ == null) {
          return postions_.get(index);  } else {
          return postionsBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends org.jcjxb.wsn.service.proto.DataType.PositionOrBuilder> 
           getPostionsOrBuilderList() {
        if (postionsBuilder_ != null) {
          return postionsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(postions_);
        }
      }
      public org.jcjxb.wsn.service.proto.DataType.Position.Builder addPostionsBuilder() {
        return getPostionsFieldBuilder().addBuilder(
            org.jcjxb.wsn.service.proto.DataType.Position.getDefaultInstance());
      }
      public org.jcjxb.wsn.service.proto.DataType.Position.Builder addPostionsBuilder(
          int index) {
        return getPostionsFieldBuilder().addBuilder(
            index, org.jcjxb.wsn.service.proto.DataType.Position.getDefaultInstance());
      }
      public java.util.List<org.jcjxb.wsn.service.proto.DataType.Position.Builder> 
           getPostionsBuilderList() {
        return getPostionsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          org.jcjxb.wsn.service.proto.DataType.Position, org.jcjxb.wsn.service.proto.DataType.Position.Builder, org.jcjxb.wsn.service.proto.DataType.PositionOrBuilder> 
          getPostionsFieldBuilder() {
        if (postionsBuilder_ == null) {
          postionsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              org.jcjxb.wsn.service.proto.DataType.Position, org.jcjxb.wsn.service.proto.DataType.Position.Builder, org.jcjxb.wsn.service.proto.DataType.PositionOrBuilder>(
                  postions_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          postions_ = null;
        }
        return postionsBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:org.jcjxb.wsn.service.PositionList)
    }
    
    static {
      defaultInstance = new PositionList(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:org.jcjxb.wsn.service.PositionList)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_jcjxb_wsn_service_Position_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_jcjxb_wsn_service_Position_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_jcjxb_wsn_service_PositionList_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_jcjxb_wsn_service_PositionList_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016DataType.proto\022\025org.jcjxb.wsn.service\"" +
      "+\n\010Position\022\t\n\001x\030\001 \001(\001\022\t\n\001y\030\002 \001(\001\022\t\n\001z\030\003" +
      " \001(\001\"x\n\014PositionList\0225\n\ndeployType\030\001 \001(\016" +
      "2!.org.jcjxb.wsn.service.DeployType\0221\n\010p" +
      "ostions\030\002 \003(\0132\037.org.jcjxb.wsn.service.Po" +
      "sition*:\n\nDeployType\022\n\n\006RANDOM\020\000\022\n\n\006STAT" +
      "IC\020\001\022\010\n\004GRID\020\002\022\n\n\006CIRCLE\020\003B\'\n\033org.jcjxb." +
      "wsn.service.protoB\010DataType"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_org_jcjxb_wsn_service_Position_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_org_jcjxb_wsn_service_Position_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_jcjxb_wsn_service_Position_descriptor,
              new java.lang.String[] { "X", "Y", "Z", },
              org.jcjxb.wsn.service.proto.DataType.Position.class,
              org.jcjxb.wsn.service.proto.DataType.Position.Builder.class);
          internal_static_org_jcjxb_wsn_service_PositionList_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_org_jcjxb_wsn_service_PositionList_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_jcjxb_wsn_service_PositionList_descriptor,
              new java.lang.String[] { "DeployType", "Postions", },
              org.jcjxb.wsn.service.proto.DataType.PositionList.class,
              org.jcjxb.wsn.service.proto.DataType.PositionList.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
