// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MasterService.proto

package org.jcjxb.wsn.service.proto;

public final class MasterService {
  private MasterService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface LVTSyncRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional int64 localTime = 1;
    boolean hasLocalTime();
    long getLocalTime();
  }
  public static final class LVTSyncRequest extends
      com.google.protobuf.GeneratedMessage
      implements LVTSyncRequestOrBuilder {
    // Use LVTSyncRequest.newBuilder() to construct.
    private LVTSyncRequest(Builder builder) {
      super(builder);
    }
    private LVTSyncRequest(boolean noInit) {}
    
    private static final LVTSyncRequest defaultInstance;
    public static LVTSyncRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public LVTSyncRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.jcjxb.wsn.service.proto.MasterService.internal_static_org_jcjxb_wsn_service_LVTSyncRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.jcjxb.wsn.service.proto.MasterService.internal_static_org_jcjxb_wsn_service_LVTSyncRequest_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional int64 localTime = 1;
    public static final int LOCALTIME_FIELD_NUMBER = 1;
    private long localTime_;
    public boolean hasLocalTime() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public long getLocalTime() {
      return localTime_;
    }
    
    private void initFields() {
      localTime_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, localTime_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, localTime_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.jcjxb.wsn.service.proto.MasterService.LVTSyncRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.jcjxb.wsn.service.proto.MasterService.LVTSyncRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.jcjxb.wsn.service.proto.MasterService.LVTSyncRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.jcjxb.wsn.service.proto.MasterService.LVTSyncRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.jcjxb.wsn.service.proto.MasterService.LVTSyncRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.jcjxb.wsn.service.proto.MasterService.LVTSyncRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.jcjxb.wsn.service.proto.MasterService.LVTSyncRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.jcjxb.wsn.service.proto.MasterService.LVTSyncRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.jcjxb.wsn.service.proto.MasterService.LVTSyncRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.jcjxb.wsn.service.proto.MasterService.LVTSyncRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.jcjxb.wsn.service.proto.MasterService.LVTSyncRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.jcjxb.wsn.service.proto.MasterService.LVTSyncRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.jcjxb.wsn.service.proto.MasterService.internal_static_org_jcjxb_wsn_service_LVTSyncRequest_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.jcjxb.wsn.service.proto.MasterService.internal_static_org_jcjxb_wsn_service_LVTSyncRequest_fieldAccessorTable;
      }
      
      // Construct using org.jcjxb.wsn.service.proto.MasterService.LVTSyncRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        localTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.jcjxb.wsn.service.proto.MasterService.LVTSyncRequest.getDescriptor();
      }
      
      public org.jcjxb.wsn.service.proto.MasterService.LVTSyncRequest getDefaultInstanceForType() {
        return org.jcjxb.wsn.service.proto.MasterService.LVTSyncRequest.getDefaultInstance();
      }
      
      public org.jcjxb.wsn.service.proto.MasterService.LVTSyncRequest build() {
        org.jcjxb.wsn.service.proto.MasterService.LVTSyncRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.jcjxb.wsn.service.proto.MasterService.LVTSyncRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.jcjxb.wsn.service.proto.MasterService.LVTSyncRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.jcjxb.wsn.service.proto.MasterService.LVTSyncRequest buildPartial() {
        org.jcjxb.wsn.service.proto.MasterService.LVTSyncRequest result = new org.jcjxb.wsn.service.proto.MasterService.LVTSyncRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.localTime_ = localTime_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.jcjxb.wsn.service.proto.MasterService.LVTSyncRequest) {
          return mergeFrom((org.jcjxb.wsn.service.proto.MasterService.LVTSyncRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.jcjxb.wsn.service.proto.MasterService.LVTSyncRequest other) {
        if (other == org.jcjxb.wsn.service.proto.MasterService.LVTSyncRequest.getDefaultInstance()) return this;
        if (other.hasLocalTime()) {
          setLocalTime(other.getLocalTime());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              localTime_ = input.readInt64();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional int64 localTime = 1;
      private long localTime_ ;
      public boolean hasLocalTime() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public long getLocalTime() {
        return localTime_;
      }
      public Builder setLocalTime(long value) {
        bitField0_ |= 0x00000001;
        localTime_ = value;
        onChanged();
        return this;
      }
      public Builder clearLocalTime() {
        bitField0_ = (bitField0_ & ~0x00000001);
        localTime_ = 0L;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:org.jcjxb.wsn.service.LVTSyncRequest)
    }
    
    static {
      defaultInstance = new LVTSyncRequest(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:org.jcjxb.wsn.service.LVTSyncRequest)
  }
  
  public static abstract class MService
      implements com.google.protobuf.Service {
    protected MService() {}
    
    public interface Interface {
      public abstract void sync(
          com.google.protobuf.RpcController controller,
          org.jcjxb.wsn.service.proto.MasterService.LVTSyncRequest request,
          com.google.protobuf.RpcCallback<org.jcjxb.wsn.service.proto.BasicDataType.Empty> done);
      
    }
    
    public static com.google.protobuf.Service newReflectiveService(
        final Interface impl) {
      return new MService() {
        @java.lang.Override
        public  void sync(
            com.google.protobuf.RpcController controller,
            org.jcjxb.wsn.service.proto.MasterService.LVTSyncRequest request,
            com.google.protobuf.RpcCallback<org.jcjxb.wsn.service.proto.BasicDataType.Empty> done) {
          impl.sync(controller, request, done);
        }
        
      };
    }
    
    public static com.google.protobuf.BlockingService
        newReflectiveBlockingService(final BlockingInterface impl) {
      return new com.google.protobuf.BlockingService() {
        public final com.google.protobuf.Descriptors.ServiceDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }
        
        public final com.google.protobuf.Message callBlockingMethod(
            com.google.protobuf.Descriptors.MethodDescriptor method,
            com.google.protobuf.RpcController controller,
            com.google.protobuf.Message request)
            throws com.google.protobuf.ServiceException {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.callBlockingMethod() given method descriptor for " +
              "wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return impl.sync(controller, (org.jcjxb.wsn.service.proto.MasterService.LVTSyncRequest)request);
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }
        
        public final com.google.protobuf.Message
            getRequestPrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getRequestPrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return org.jcjxb.wsn.service.proto.MasterService.LVTSyncRequest.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }
        
        public final com.google.protobuf.Message
            getResponsePrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getResponsePrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return org.jcjxb.wsn.service.proto.BasicDataType.Empty.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }
        
      };
    }
    
    public abstract void sync(
        com.google.protobuf.RpcController controller,
        org.jcjxb.wsn.service.proto.MasterService.LVTSyncRequest request,
        com.google.protobuf.RpcCallback<org.jcjxb.wsn.service.proto.BasicDataType.Empty> done);
    
    public static final
        com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptor() {
      return org.jcjxb.wsn.service.proto.MasterService.getDescriptor().getServices().get(0);
    }
    public final com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    
    public final void callMethod(
        com.google.protobuf.Descriptors.MethodDescriptor method,
        com.google.protobuf.RpcController controller,
        com.google.protobuf.Message request,
        com.google.protobuf.RpcCallback<
          com.google.protobuf.Message> done) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.callMethod() given method descriptor for wrong " +
          "service type.");
      }
      switch(method.getIndex()) {
        case 0:
          this.sync(controller, (org.jcjxb.wsn.service.proto.MasterService.LVTSyncRequest)request,
            com.google.protobuf.RpcUtil.<org.jcjxb.wsn.service.proto.BasicDataType.Empty>specializeCallback(
              done));
          return;
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }
    
    public final com.google.protobuf.Message
        getRequestPrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getRequestPrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return org.jcjxb.wsn.service.proto.MasterService.LVTSyncRequest.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }
    
    public final com.google.protobuf.Message
        getResponsePrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getResponsePrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return org.jcjxb.wsn.service.proto.BasicDataType.Empty.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }
    
    public static Stub newStub(
        com.google.protobuf.RpcChannel channel) {
      return new Stub(channel);
    }
    
    public static final class Stub extends org.jcjxb.wsn.service.proto.MasterService.MService implements Interface {
      private Stub(com.google.protobuf.RpcChannel channel) {
        this.channel = channel;
      }
      
      private final com.google.protobuf.RpcChannel channel;
      
      public com.google.protobuf.RpcChannel getChannel() {
        return channel;
      }
      
      public  void sync(
          com.google.protobuf.RpcController controller,
          org.jcjxb.wsn.service.proto.MasterService.LVTSyncRequest request,
          com.google.protobuf.RpcCallback<org.jcjxb.wsn.service.proto.BasicDataType.Empty> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          org.jcjxb.wsn.service.proto.BasicDataType.Empty.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            org.jcjxb.wsn.service.proto.BasicDataType.Empty.class,
            org.jcjxb.wsn.service.proto.BasicDataType.Empty.getDefaultInstance()));
      }
    }
    
    public static BlockingInterface newBlockingStub(
        com.google.protobuf.BlockingRpcChannel channel) {
      return new BlockingStub(channel);
    }
    
    public interface BlockingInterface {
      public org.jcjxb.wsn.service.proto.BasicDataType.Empty sync(
          com.google.protobuf.RpcController controller,
          org.jcjxb.wsn.service.proto.MasterService.LVTSyncRequest request)
          throws com.google.protobuf.ServiceException;
    }
    
    private static final class BlockingStub implements BlockingInterface {
      private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
        this.channel = channel;
      }
      
      private final com.google.protobuf.BlockingRpcChannel channel;
      
      public org.jcjxb.wsn.service.proto.BasicDataType.Empty sync(
          com.google.protobuf.RpcController controller,
          org.jcjxb.wsn.service.proto.MasterService.LVTSyncRequest request)
          throws com.google.protobuf.ServiceException {
        return (org.jcjxb.wsn.service.proto.BasicDataType.Empty) channel.callBlockingMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          org.jcjxb.wsn.service.proto.BasicDataType.Empty.getDefaultInstance());
      }
      
    }
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_jcjxb_wsn_service_LVTSyncRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_jcjxb_wsn_service_LVTSyncRequest_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023MasterService.proto\022\025org.jcjxb.wsn.ser" +
      "vice\032\023BasicDataType.proto\"#\n\016LVTSyncRequ" +
      "est\022\021\n\tlocalTime\030\001 \001(\0032W\n\010MService\022K\n\004sy" +
      "nc\022%.org.jcjxb.wsn.service.LVTSyncReques" +
      "t\032\034.org.jcjxb.wsn.service.EmptyB/\n\033org.j" +
      "cjxb.wsn.service.protoB\rMasterService\210\001\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_org_jcjxb_wsn_service_LVTSyncRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_org_jcjxb_wsn_service_LVTSyncRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_jcjxb_wsn_service_LVTSyncRequest_descriptor,
              new java.lang.String[] { "LocalTime", },
              org.jcjxb.wsn.service.proto.MasterService.LVTSyncRequest.class,
              org.jcjxb.wsn.service.proto.MasterService.LVTSyncRequest.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.jcjxb.wsn.service.proto.BasicDataType.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
