// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SimulatorConfig.proto

package org.jcjxb.wsn.service.proto;

public final class SimulatorConfig {
  private SimulatorConfig() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface HostConfigOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional .org.jcjxb.wsn.service.Host masterHost = 1;
    boolean hasMasterHost();
    org.jcjxb.wsn.service.proto.BasicDataType.Host getMasterHost();
    org.jcjxb.wsn.service.proto.BasicDataType.HostOrBuilder getMasterHostOrBuilder();
    
    // repeated .org.jcjxb.wsn.service.Host slaveHost = 2;
    java.util.List<org.jcjxb.wsn.service.proto.BasicDataType.Host> 
        getSlaveHostList();
    org.jcjxb.wsn.service.proto.BasicDataType.Host getSlaveHost(int index);
    int getSlaveHostCount();
    java.util.List<? extends org.jcjxb.wsn.service.proto.BasicDataType.HostOrBuilder> 
        getSlaveHostOrBuilderList();
    org.jcjxb.wsn.service.proto.BasicDataType.HostOrBuilder getSlaveHostOrBuilder(
        int index);
  }
  public static final class HostConfig extends
      com.google.protobuf.GeneratedMessage
      implements HostConfigOrBuilder {
    // Use HostConfig.newBuilder() to construct.
    private HostConfig(Builder builder) {
      super(builder);
    }
    private HostConfig(boolean noInit) {}
    
    private static final HostConfig defaultInstance;
    public static HostConfig getDefaultInstance() {
      return defaultInstance;
    }
    
    public HostConfig getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.jcjxb.wsn.service.proto.SimulatorConfig.internal_static_org_jcjxb_wsn_service_HostConfig_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.jcjxb.wsn.service.proto.SimulatorConfig.internal_static_org_jcjxb_wsn_service_HostConfig_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional .org.jcjxb.wsn.service.Host masterHost = 1;
    public static final int MASTERHOST_FIELD_NUMBER = 1;
    private org.jcjxb.wsn.service.proto.BasicDataType.Host masterHost_;
    public boolean hasMasterHost() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public org.jcjxb.wsn.service.proto.BasicDataType.Host getMasterHost() {
      return masterHost_;
    }
    public org.jcjxb.wsn.service.proto.BasicDataType.HostOrBuilder getMasterHostOrBuilder() {
      return masterHost_;
    }
    
    // repeated .org.jcjxb.wsn.service.Host slaveHost = 2;
    public static final int SLAVEHOST_FIELD_NUMBER = 2;
    private java.util.List<org.jcjxb.wsn.service.proto.BasicDataType.Host> slaveHost_;
    public java.util.List<org.jcjxb.wsn.service.proto.BasicDataType.Host> getSlaveHostList() {
      return slaveHost_;
    }
    public java.util.List<? extends org.jcjxb.wsn.service.proto.BasicDataType.HostOrBuilder> 
        getSlaveHostOrBuilderList() {
      return slaveHost_;
    }
    public int getSlaveHostCount() {
      return slaveHost_.size();
    }
    public org.jcjxb.wsn.service.proto.BasicDataType.Host getSlaveHost(int index) {
      return slaveHost_.get(index);
    }
    public org.jcjxb.wsn.service.proto.BasicDataType.HostOrBuilder getSlaveHostOrBuilder(
        int index) {
      return slaveHost_.get(index);
    }
    
    private void initFields() {
      masterHost_ = org.jcjxb.wsn.service.proto.BasicDataType.Host.getDefaultInstance();
      slaveHost_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, masterHost_);
      }
      for (int i = 0; i < slaveHost_.size(); i++) {
        output.writeMessage(2, slaveHost_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, masterHost_);
      }
      for (int i = 0; i < slaveHost_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, slaveHost_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.jcjxb.wsn.service.proto.SimulatorConfig.HostConfig parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.jcjxb.wsn.service.proto.SimulatorConfig.HostConfig parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.jcjxb.wsn.service.proto.SimulatorConfig.HostConfig parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.jcjxb.wsn.service.proto.SimulatorConfig.HostConfig parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.jcjxb.wsn.service.proto.SimulatorConfig.HostConfig parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.jcjxb.wsn.service.proto.SimulatorConfig.HostConfig parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.jcjxb.wsn.service.proto.SimulatorConfig.HostConfig parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.jcjxb.wsn.service.proto.SimulatorConfig.HostConfig parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.jcjxb.wsn.service.proto.SimulatorConfig.HostConfig parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.jcjxb.wsn.service.proto.SimulatorConfig.HostConfig parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.jcjxb.wsn.service.proto.SimulatorConfig.HostConfig prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.jcjxb.wsn.service.proto.SimulatorConfig.HostConfigOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.jcjxb.wsn.service.proto.SimulatorConfig.internal_static_org_jcjxb_wsn_service_HostConfig_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.jcjxb.wsn.service.proto.SimulatorConfig.internal_static_org_jcjxb_wsn_service_HostConfig_fieldAccessorTable;
      }
      
      // Construct using org.jcjxb.wsn.service.proto.SimulatorConfig.HostConfig.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getMasterHostFieldBuilder();
          getSlaveHostFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (masterHostBuilder_ == null) {
          masterHost_ = org.jcjxb.wsn.service.proto.BasicDataType.Host.getDefaultInstance();
        } else {
          masterHostBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        if (slaveHostBuilder_ == null) {
          slaveHost_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          slaveHostBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.jcjxb.wsn.service.proto.SimulatorConfig.HostConfig.getDescriptor();
      }
      
      public org.jcjxb.wsn.service.proto.SimulatorConfig.HostConfig getDefaultInstanceForType() {
        return org.jcjxb.wsn.service.proto.SimulatorConfig.HostConfig.getDefaultInstance();
      }
      
      public org.jcjxb.wsn.service.proto.SimulatorConfig.HostConfig build() {
        org.jcjxb.wsn.service.proto.SimulatorConfig.HostConfig result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.jcjxb.wsn.service.proto.SimulatorConfig.HostConfig buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.jcjxb.wsn.service.proto.SimulatorConfig.HostConfig result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.jcjxb.wsn.service.proto.SimulatorConfig.HostConfig buildPartial() {
        org.jcjxb.wsn.service.proto.SimulatorConfig.HostConfig result = new org.jcjxb.wsn.service.proto.SimulatorConfig.HostConfig(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (masterHostBuilder_ == null) {
          result.masterHost_ = masterHost_;
        } else {
          result.masterHost_ = masterHostBuilder_.build();
        }
        if (slaveHostBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            slaveHost_ = java.util.Collections.unmodifiableList(slaveHost_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.slaveHost_ = slaveHost_;
        } else {
          result.slaveHost_ = slaveHostBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.jcjxb.wsn.service.proto.SimulatorConfig.HostConfig) {
          return mergeFrom((org.jcjxb.wsn.service.proto.SimulatorConfig.HostConfig)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.jcjxb.wsn.service.proto.SimulatorConfig.HostConfig other) {
        if (other == org.jcjxb.wsn.service.proto.SimulatorConfig.HostConfig.getDefaultInstance()) return this;
        if (other.hasMasterHost()) {
          mergeMasterHost(other.getMasterHost());
        }
        if (slaveHostBuilder_ == null) {
          if (!other.slaveHost_.isEmpty()) {
            if (slaveHost_.isEmpty()) {
              slaveHost_ = other.slaveHost_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureSlaveHostIsMutable();
              slaveHost_.addAll(other.slaveHost_);
            }
            onChanged();
          }
        } else {
          if (!other.slaveHost_.isEmpty()) {
            if (slaveHostBuilder_.isEmpty()) {
              slaveHostBuilder_.dispose();
              slaveHostBuilder_ = null;
              slaveHost_ = other.slaveHost_;
              bitField0_ = (bitField0_ & ~0x00000002);
              slaveHostBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getSlaveHostFieldBuilder() : null;
            } else {
              slaveHostBuilder_.addAllMessages(other.slaveHost_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              org.jcjxb.wsn.service.proto.BasicDataType.Host.Builder subBuilder = org.jcjxb.wsn.service.proto.BasicDataType.Host.newBuilder();
              if (hasMasterHost()) {
                subBuilder.mergeFrom(getMasterHost());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setMasterHost(subBuilder.buildPartial());
              break;
            }
            case 18: {
              org.jcjxb.wsn.service.proto.BasicDataType.Host.Builder subBuilder = org.jcjxb.wsn.service.proto.BasicDataType.Host.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addSlaveHost(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional .org.jcjxb.wsn.service.Host masterHost = 1;
      private org.jcjxb.wsn.service.proto.BasicDataType.Host masterHost_ = org.jcjxb.wsn.service.proto.BasicDataType.Host.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          org.jcjxb.wsn.service.proto.BasicDataType.Host, org.jcjxb.wsn.service.proto.BasicDataType.Host.Builder, org.jcjxb.wsn.service.proto.BasicDataType.HostOrBuilder> masterHostBuilder_;
      public boolean hasMasterHost() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public org.jcjxb.wsn.service.proto.BasicDataType.Host getMasterHost() {
        if (masterHostBuilder_ == null) {
          return masterHost_;
        } else {
          return masterHostBuilder_.getMessage();
        }
      }
      public Builder setMasterHost(org.jcjxb.wsn.service.proto.BasicDataType.Host value) {
        if (masterHostBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          masterHost_ = value;
          onChanged();
        } else {
          masterHostBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder setMasterHost(
          org.jcjxb.wsn.service.proto.BasicDataType.Host.Builder builderForValue) {
        if (masterHostBuilder_ == null) {
          masterHost_ = builderForValue.build();
          onChanged();
        } else {
          masterHostBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder mergeMasterHost(org.jcjxb.wsn.service.proto.BasicDataType.Host value) {
        if (masterHostBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              masterHost_ != org.jcjxb.wsn.service.proto.BasicDataType.Host.getDefaultInstance()) {
            masterHost_ =
              org.jcjxb.wsn.service.proto.BasicDataType.Host.newBuilder(masterHost_).mergeFrom(value).buildPartial();
          } else {
            masterHost_ = value;
          }
          onChanged();
        } else {
          masterHostBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder clearMasterHost() {
        if (masterHostBuilder_ == null) {
          masterHost_ = org.jcjxb.wsn.service.proto.BasicDataType.Host.getDefaultInstance();
          onChanged();
        } else {
          masterHostBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      public org.jcjxb.wsn.service.proto.BasicDataType.Host.Builder getMasterHostBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getMasterHostFieldBuilder().getBuilder();
      }
      public org.jcjxb.wsn.service.proto.BasicDataType.HostOrBuilder getMasterHostOrBuilder() {
        if (masterHostBuilder_ != null) {
          return masterHostBuilder_.getMessageOrBuilder();
        } else {
          return masterHost_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          org.jcjxb.wsn.service.proto.BasicDataType.Host, org.jcjxb.wsn.service.proto.BasicDataType.Host.Builder, org.jcjxb.wsn.service.proto.BasicDataType.HostOrBuilder> 
          getMasterHostFieldBuilder() {
        if (masterHostBuilder_ == null) {
          masterHostBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              org.jcjxb.wsn.service.proto.BasicDataType.Host, org.jcjxb.wsn.service.proto.BasicDataType.Host.Builder, org.jcjxb.wsn.service.proto.BasicDataType.HostOrBuilder>(
                  masterHost_,
                  getParentForChildren(),
                  isClean());
          masterHost_ = null;
        }
        return masterHostBuilder_;
      }
      
      // repeated .org.jcjxb.wsn.service.Host slaveHost = 2;
      private java.util.List<org.jcjxb.wsn.service.proto.BasicDataType.Host> slaveHost_ =
        java.util.Collections.emptyList();
      private void ensureSlaveHostIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          slaveHost_ = new java.util.ArrayList<org.jcjxb.wsn.service.proto.BasicDataType.Host>(slaveHost_);
          bitField0_ |= 0x00000002;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          org.jcjxb.wsn.service.proto.BasicDataType.Host, org.jcjxb.wsn.service.proto.BasicDataType.Host.Builder, org.jcjxb.wsn.service.proto.BasicDataType.HostOrBuilder> slaveHostBuilder_;
      
      public java.util.List<org.jcjxb.wsn.service.proto.BasicDataType.Host> getSlaveHostList() {
        if (slaveHostBuilder_ == null) {
          return java.util.Collections.unmodifiableList(slaveHost_);
        } else {
          return slaveHostBuilder_.getMessageList();
        }
      }
      public int getSlaveHostCount() {
        if (slaveHostBuilder_ == null) {
          return slaveHost_.size();
        } else {
          return slaveHostBuilder_.getCount();
        }
      }
      public org.jcjxb.wsn.service.proto.BasicDataType.Host getSlaveHost(int index) {
        if (slaveHostBuilder_ == null) {
          return slaveHost_.get(index);
        } else {
          return slaveHostBuilder_.getMessage(index);
        }
      }
      public Builder setSlaveHost(
          int index, org.jcjxb.wsn.service.proto.BasicDataType.Host value) {
        if (slaveHostBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSlaveHostIsMutable();
          slaveHost_.set(index, value);
          onChanged();
        } else {
          slaveHostBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setSlaveHost(
          int index, org.jcjxb.wsn.service.proto.BasicDataType.Host.Builder builderForValue) {
        if (slaveHostBuilder_ == null) {
          ensureSlaveHostIsMutable();
          slaveHost_.set(index, builderForValue.build());
          onChanged();
        } else {
          slaveHostBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addSlaveHost(org.jcjxb.wsn.service.proto.BasicDataType.Host value) {
        if (slaveHostBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSlaveHostIsMutable();
          slaveHost_.add(value);
          onChanged();
        } else {
          slaveHostBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addSlaveHost(
          int index, org.jcjxb.wsn.service.proto.BasicDataType.Host value) {
        if (slaveHostBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSlaveHostIsMutable();
          slaveHost_.add(index, value);
          onChanged();
        } else {
          slaveHostBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addSlaveHost(
          org.jcjxb.wsn.service.proto.BasicDataType.Host.Builder builderForValue) {
        if (slaveHostBuilder_ == null) {
          ensureSlaveHostIsMutable();
          slaveHost_.add(builderForValue.build());
          onChanged();
        } else {
          slaveHostBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addSlaveHost(
          int index, org.jcjxb.wsn.service.proto.BasicDataType.Host.Builder builderForValue) {
        if (slaveHostBuilder_ == null) {
          ensureSlaveHostIsMutable();
          slaveHost_.add(index, builderForValue.build());
          onChanged();
        } else {
          slaveHostBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllSlaveHost(
          java.lang.Iterable<? extends org.jcjxb.wsn.service.proto.BasicDataType.Host> values) {
        if (slaveHostBuilder_ == null) {
          ensureSlaveHostIsMutable();
          super.addAll(values, slaveHost_);
          onChanged();
        } else {
          slaveHostBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearSlaveHost() {
        if (slaveHostBuilder_ == null) {
          slaveHost_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          slaveHostBuilder_.clear();
        }
        return this;
      }
      public Builder removeSlaveHost(int index) {
        if (slaveHostBuilder_ == null) {
          ensureSlaveHostIsMutable();
          slaveHost_.remove(index);
          onChanged();
        } else {
          slaveHostBuilder_.remove(index);
        }
        return this;
      }
      public org.jcjxb.wsn.service.proto.BasicDataType.Host.Builder getSlaveHostBuilder(
          int index) {
        return getSlaveHostFieldBuilder().getBuilder(index);
      }
      public org.jcjxb.wsn.service.proto.BasicDataType.HostOrBuilder getSlaveHostOrBuilder(
          int index) {
        if (slaveHostBuilder_ == null) {
          return slaveHost_.get(index);  } else {
          return slaveHostBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends org.jcjxb.wsn.service.proto.BasicDataType.HostOrBuilder> 
           getSlaveHostOrBuilderList() {
        if (slaveHostBuilder_ != null) {
          return slaveHostBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(slaveHost_);
        }
      }
      public org.jcjxb.wsn.service.proto.BasicDataType.Host.Builder addSlaveHostBuilder() {
        return getSlaveHostFieldBuilder().addBuilder(
            org.jcjxb.wsn.service.proto.BasicDataType.Host.getDefaultInstance());
      }
      public org.jcjxb.wsn.service.proto.BasicDataType.Host.Builder addSlaveHostBuilder(
          int index) {
        return getSlaveHostFieldBuilder().addBuilder(
            index, org.jcjxb.wsn.service.proto.BasicDataType.Host.getDefaultInstance());
      }
      public java.util.List<org.jcjxb.wsn.service.proto.BasicDataType.Host.Builder> 
           getSlaveHostBuilderList() {
        return getSlaveHostFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          org.jcjxb.wsn.service.proto.BasicDataType.Host, org.jcjxb.wsn.service.proto.BasicDataType.Host.Builder, org.jcjxb.wsn.service.proto.BasicDataType.HostOrBuilder> 
          getSlaveHostFieldBuilder() {
        if (slaveHostBuilder_ == null) {
          slaveHostBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              org.jcjxb.wsn.service.proto.BasicDataType.Host, org.jcjxb.wsn.service.proto.BasicDataType.Host.Builder, org.jcjxb.wsn.service.proto.BasicDataType.HostOrBuilder>(
                  slaveHost_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          slaveHost_ = null;
        }
        return slaveHostBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:org.jcjxb.wsn.service.HostConfig)
    }
    
    static {
      defaultInstance = new HostConfig(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:org.jcjxb.wsn.service.HostConfig)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_jcjxb_wsn_service_HostConfig_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_jcjxb_wsn_service_HostConfig_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025SimulatorConfig.proto\022\025org.jcjxb.wsn.s" +
      "ervice\032\023BasicDataType.proto\"m\n\nHostConfi" +
      "g\022/\n\nmasterHost\030\001 \001(\0132\033.org.jcjxb.wsn.se" +
      "rvice.Host\022.\n\tslaveHost\030\002 \003(\0132\033.org.jcjx" +
      "b.wsn.service.HostB.\n\033org.jcjxb.wsn.serv" +
      "ice.protoB\017SimulatorConfig"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_org_jcjxb_wsn_service_HostConfig_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_org_jcjxb_wsn_service_HostConfig_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_jcjxb_wsn_service_HostConfig_descriptor,
              new java.lang.String[] { "MasterHost", "SlaveHost", },
              org.jcjxb.wsn.service.proto.SimulatorConfig.HostConfig.class,
              org.jcjxb.wsn.service.proto.SimulatorConfig.HostConfig.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.jcjxb.wsn.service.proto.BasicDataType.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
