// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SlaveService.proto

package org.jcjxb.wsn.service.proto;

public final class SlaveService {
  private SlaveService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface InitSimCmdOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional .org.jcjxb.wsn.service.SensorsOnHost sendorsOnThisHost = 1;
    boolean hasSendorsOnThisHost();
    org.jcjxb.wsn.service.proto.BasicDataType.SensorsOnHost getSendorsOnThisHost();
    org.jcjxb.wsn.service.proto.BasicDataType.SensorsOnHostOrBuilder getSendorsOnThisHostOrBuilder();
    
    // repeated .org.jcjxb.wsn.service.SensorsOnHost sendorsOnLeftHosts = 2;
    java.util.List<org.jcjxb.wsn.service.proto.BasicDataType.SensorsOnHost> 
        getSendorsOnLeftHostsList();
    org.jcjxb.wsn.service.proto.BasicDataType.SensorsOnHost getSendorsOnLeftHosts(int index);
    int getSendorsOnLeftHostsCount();
    java.util.List<? extends org.jcjxb.wsn.service.proto.BasicDataType.SensorsOnHostOrBuilder> 
        getSendorsOnLeftHostsOrBuilderList();
    org.jcjxb.wsn.service.proto.BasicDataType.SensorsOnHostOrBuilder getSendorsOnLeftHostsOrBuilder(
        int index);
  }
  public static final class InitSimCmd extends
      com.google.protobuf.GeneratedMessage
      implements InitSimCmdOrBuilder {
    // Use InitSimCmd.newBuilder() to construct.
    private InitSimCmd(Builder builder) {
      super(builder);
    }
    private InitSimCmd(boolean noInit) {}
    
    private static final InitSimCmd defaultInstance;
    public static InitSimCmd getDefaultInstance() {
      return defaultInstance;
    }
    
    public InitSimCmd getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.jcjxb.wsn.service.proto.SlaveService.internal_static_org_jcjxb_wsn_service_InitSimCmd_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.jcjxb.wsn.service.proto.SlaveService.internal_static_org_jcjxb_wsn_service_InitSimCmd_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional .org.jcjxb.wsn.service.SensorsOnHost sendorsOnThisHost = 1;
    public static final int SENDORSONTHISHOST_FIELD_NUMBER = 1;
    private org.jcjxb.wsn.service.proto.BasicDataType.SensorsOnHost sendorsOnThisHost_;
    public boolean hasSendorsOnThisHost() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public org.jcjxb.wsn.service.proto.BasicDataType.SensorsOnHost getSendorsOnThisHost() {
      return sendorsOnThisHost_;
    }
    public org.jcjxb.wsn.service.proto.BasicDataType.SensorsOnHostOrBuilder getSendorsOnThisHostOrBuilder() {
      return sendorsOnThisHost_;
    }
    
    // repeated .org.jcjxb.wsn.service.SensorsOnHost sendorsOnLeftHosts = 2;
    public static final int SENDORSONLEFTHOSTS_FIELD_NUMBER = 2;
    private java.util.List<org.jcjxb.wsn.service.proto.BasicDataType.SensorsOnHost> sendorsOnLeftHosts_;
    public java.util.List<org.jcjxb.wsn.service.proto.BasicDataType.SensorsOnHost> getSendorsOnLeftHostsList() {
      return sendorsOnLeftHosts_;
    }
    public java.util.List<? extends org.jcjxb.wsn.service.proto.BasicDataType.SensorsOnHostOrBuilder> 
        getSendorsOnLeftHostsOrBuilderList() {
      return sendorsOnLeftHosts_;
    }
    public int getSendorsOnLeftHostsCount() {
      return sendorsOnLeftHosts_.size();
    }
    public org.jcjxb.wsn.service.proto.BasicDataType.SensorsOnHost getSendorsOnLeftHosts(int index) {
      return sendorsOnLeftHosts_.get(index);
    }
    public org.jcjxb.wsn.service.proto.BasicDataType.SensorsOnHostOrBuilder getSendorsOnLeftHostsOrBuilder(
        int index) {
      return sendorsOnLeftHosts_.get(index);
    }
    
    private void initFields() {
      sendorsOnThisHost_ = org.jcjxb.wsn.service.proto.BasicDataType.SensorsOnHost.getDefaultInstance();
      sendorsOnLeftHosts_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, sendorsOnThisHost_);
      }
      for (int i = 0; i < sendorsOnLeftHosts_.size(); i++) {
        output.writeMessage(2, sendorsOnLeftHosts_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, sendorsOnThisHost_);
      }
      for (int i = 0; i < sendorsOnLeftHosts_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, sendorsOnLeftHosts_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.jcjxb.wsn.service.proto.SlaveService.InitSimCmd parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.jcjxb.wsn.service.proto.SlaveService.InitSimCmd parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.jcjxb.wsn.service.proto.SlaveService.InitSimCmd parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.jcjxb.wsn.service.proto.SlaveService.InitSimCmd parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.jcjxb.wsn.service.proto.SlaveService.InitSimCmd parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.jcjxb.wsn.service.proto.SlaveService.InitSimCmd parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.jcjxb.wsn.service.proto.SlaveService.InitSimCmd parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.jcjxb.wsn.service.proto.SlaveService.InitSimCmd parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.jcjxb.wsn.service.proto.SlaveService.InitSimCmd parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.jcjxb.wsn.service.proto.SlaveService.InitSimCmd parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.jcjxb.wsn.service.proto.SlaveService.InitSimCmd prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.jcjxb.wsn.service.proto.SlaveService.InitSimCmdOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.jcjxb.wsn.service.proto.SlaveService.internal_static_org_jcjxb_wsn_service_InitSimCmd_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.jcjxb.wsn.service.proto.SlaveService.internal_static_org_jcjxb_wsn_service_InitSimCmd_fieldAccessorTable;
      }
      
      // Construct using org.jcjxb.wsn.service.proto.SlaveService.InitSimCmd.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getSendorsOnThisHostFieldBuilder();
          getSendorsOnLeftHostsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (sendorsOnThisHostBuilder_ == null) {
          sendorsOnThisHost_ = org.jcjxb.wsn.service.proto.BasicDataType.SensorsOnHost.getDefaultInstance();
        } else {
          sendorsOnThisHostBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        if (sendorsOnLeftHostsBuilder_ == null) {
          sendorsOnLeftHosts_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          sendorsOnLeftHostsBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.jcjxb.wsn.service.proto.SlaveService.InitSimCmd.getDescriptor();
      }
      
      public org.jcjxb.wsn.service.proto.SlaveService.InitSimCmd getDefaultInstanceForType() {
        return org.jcjxb.wsn.service.proto.SlaveService.InitSimCmd.getDefaultInstance();
      }
      
      public org.jcjxb.wsn.service.proto.SlaveService.InitSimCmd build() {
        org.jcjxb.wsn.service.proto.SlaveService.InitSimCmd result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.jcjxb.wsn.service.proto.SlaveService.InitSimCmd buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.jcjxb.wsn.service.proto.SlaveService.InitSimCmd result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.jcjxb.wsn.service.proto.SlaveService.InitSimCmd buildPartial() {
        org.jcjxb.wsn.service.proto.SlaveService.InitSimCmd result = new org.jcjxb.wsn.service.proto.SlaveService.InitSimCmd(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (sendorsOnThisHostBuilder_ == null) {
          result.sendorsOnThisHost_ = sendorsOnThisHost_;
        } else {
          result.sendorsOnThisHost_ = sendorsOnThisHostBuilder_.build();
        }
        if (sendorsOnLeftHostsBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            sendorsOnLeftHosts_ = java.util.Collections.unmodifiableList(sendorsOnLeftHosts_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.sendorsOnLeftHosts_ = sendorsOnLeftHosts_;
        } else {
          result.sendorsOnLeftHosts_ = sendorsOnLeftHostsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.jcjxb.wsn.service.proto.SlaveService.InitSimCmd) {
          return mergeFrom((org.jcjxb.wsn.service.proto.SlaveService.InitSimCmd)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.jcjxb.wsn.service.proto.SlaveService.InitSimCmd other) {
        if (other == org.jcjxb.wsn.service.proto.SlaveService.InitSimCmd.getDefaultInstance()) return this;
        if (other.hasSendorsOnThisHost()) {
          mergeSendorsOnThisHost(other.getSendorsOnThisHost());
        }
        if (sendorsOnLeftHostsBuilder_ == null) {
          if (!other.sendorsOnLeftHosts_.isEmpty()) {
            if (sendorsOnLeftHosts_.isEmpty()) {
              sendorsOnLeftHosts_ = other.sendorsOnLeftHosts_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureSendorsOnLeftHostsIsMutable();
              sendorsOnLeftHosts_.addAll(other.sendorsOnLeftHosts_);
            }
            onChanged();
          }
        } else {
          if (!other.sendorsOnLeftHosts_.isEmpty()) {
            if (sendorsOnLeftHostsBuilder_.isEmpty()) {
              sendorsOnLeftHostsBuilder_.dispose();
              sendorsOnLeftHostsBuilder_ = null;
              sendorsOnLeftHosts_ = other.sendorsOnLeftHosts_;
              bitField0_ = (bitField0_ & ~0x00000002);
              sendorsOnLeftHostsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getSendorsOnLeftHostsFieldBuilder() : null;
            } else {
              sendorsOnLeftHostsBuilder_.addAllMessages(other.sendorsOnLeftHosts_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              org.jcjxb.wsn.service.proto.BasicDataType.SensorsOnHost.Builder subBuilder = org.jcjxb.wsn.service.proto.BasicDataType.SensorsOnHost.newBuilder();
              if (hasSendorsOnThisHost()) {
                subBuilder.mergeFrom(getSendorsOnThisHost());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setSendorsOnThisHost(subBuilder.buildPartial());
              break;
            }
            case 18: {
              org.jcjxb.wsn.service.proto.BasicDataType.SensorsOnHost.Builder subBuilder = org.jcjxb.wsn.service.proto.BasicDataType.SensorsOnHost.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addSendorsOnLeftHosts(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional .org.jcjxb.wsn.service.SensorsOnHost sendorsOnThisHost = 1;
      private org.jcjxb.wsn.service.proto.BasicDataType.SensorsOnHost sendorsOnThisHost_ = org.jcjxb.wsn.service.proto.BasicDataType.SensorsOnHost.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          org.jcjxb.wsn.service.proto.BasicDataType.SensorsOnHost, org.jcjxb.wsn.service.proto.BasicDataType.SensorsOnHost.Builder, org.jcjxb.wsn.service.proto.BasicDataType.SensorsOnHostOrBuilder> sendorsOnThisHostBuilder_;
      public boolean hasSendorsOnThisHost() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public org.jcjxb.wsn.service.proto.BasicDataType.SensorsOnHost getSendorsOnThisHost() {
        if (sendorsOnThisHostBuilder_ == null) {
          return sendorsOnThisHost_;
        } else {
          return sendorsOnThisHostBuilder_.getMessage();
        }
      }
      public Builder setSendorsOnThisHost(org.jcjxb.wsn.service.proto.BasicDataType.SensorsOnHost value) {
        if (sendorsOnThisHostBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          sendorsOnThisHost_ = value;
          onChanged();
        } else {
          sendorsOnThisHostBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder setSendorsOnThisHost(
          org.jcjxb.wsn.service.proto.BasicDataType.SensorsOnHost.Builder builderForValue) {
        if (sendorsOnThisHostBuilder_ == null) {
          sendorsOnThisHost_ = builderForValue.build();
          onChanged();
        } else {
          sendorsOnThisHostBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder mergeSendorsOnThisHost(org.jcjxb.wsn.service.proto.BasicDataType.SensorsOnHost value) {
        if (sendorsOnThisHostBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              sendorsOnThisHost_ != org.jcjxb.wsn.service.proto.BasicDataType.SensorsOnHost.getDefaultInstance()) {
            sendorsOnThisHost_ =
              org.jcjxb.wsn.service.proto.BasicDataType.SensorsOnHost.newBuilder(sendorsOnThisHost_).mergeFrom(value).buildPartial();
          } else {
            sendorsOnThisHost_ = value;
          }
          onChanged();
        } else {
          sendorsOnThisHostBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder clearSendorsOnThisHost() {
        if (sendorsOnThisHostBuilder_ == null) {
          sendorsOnThisHost_ = org.jcjxb.wsn.service.proto.BasicDataType.SensorsOnHost.getDefaultInstance();
          onChanged();
        } else {
          sendorsOnThisHostBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      public org.jcjxb.wsn.service.proto.BasicDataType.SensorsOnHost.Builder getSendorsOnThisHostBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getSendorsOnThisHostFieldBuilder().getBuilder();
      }
      public org.jcjxb.wsn.service.proto.BasicDataType.SensorsOnHostOrBuilder getSendorsOnThisHostOrBuilder() {
        if (sendorsOnThisHostBuilder_ != null) {
          return sendorsOnThisHostBuilder_.getMessageOrBuilder();
        } else {
          return sendorsOnThisHost_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          org.jcjxb.wsn.service.proto.BasicDataType.SensorsOnHost, org.jcjxb.wsn.service.proto.BasicDataType.SensorsOnHost.Builder, org.jcjxb.wsn.service.proto.BasicDataType.SensorsOnHostOrBuilder> 
          getSendorsOnThisHostFieldBuilder() {
        if (sendorsOnThisHostBuilder_ == null) {
          sendorsOnThisHostBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              org.jcjxb.wsn.service.proto.BasicDataType.SensorsOnHost, org.jcjxb.wsn.service.proto.BasicDataType.SensorsOnHost.Builder, org.jcjxb.wsn.service.proto.BasicDataType.SensorsOnHostOrBuilder>(
                  sendorsOnThisHost_,
                  getParentForChildren(),
                  isClean());
          sendorsOnThisHost_ = null;
        }
        return sendorsOnThisHostBuilder_;
      }
      
      // repeated .org.jcjxb.wsn.service.SensorsOnHost sendorsOnLeftHosts = 2;
      private java.util.List<org.jcjxb.wsn.service.proto.BasicDataType.SensorsOnHost> sendorsOnLeftHosts_ =
        java.util.Collections.emptyList();
      private void ensureSendorsOnLeftHostsIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          sendorsOnLeftHosts_ = new java.util.ArrayList<org.jcjxb.wsn.service.proto.BasicDataType.SensorsOnHost>(sendorsOnLeftHosts_);
          bitField0_ |= 0x00000002;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          org.jcjxb.wsn.service.proto.BasicDataType.SensorsOnHost, org.jcjxb.wsn.service.proto.BasicDataType.SensorsOnHost.Builder, org.jcjxb.wsn.service.proto.BasicDataType.SensorsOnHostOrBuilder> sendorsOnLeftHostsBuilder_;
      
      public java.util.List<org.jcjxb.wsn.service.proto.BasicDataType.SensorsOnHost> getSendorsOnLeftHostsList() {
        if (sendorsOnLeftHostsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(sendorsOnLeftHosts_);
        } else {
          return sendorsOnLeftHostsBuilder_.getMessageList();
        }
      }
      public int getSendorsOnLeftHostsCount() {
        if (sendorsOnLeftHostsBuilder_ == null) {
          return sendorsOnLeftHosts_.size();
        } else {
          return sendorsOnLeftHostsBuilder_.getCount();
        }
      }
      public org.jcjxb.wsn.service.proto.BasicDataType.SensorsOnHost getSendorsOnLeftHosts(int index) {
        if (sendorsOnLeftHostsBuilder_ == null) {
          return sendorsOnLeftHosts_.get(index);
        } else {
          return sendorsOnLeftHostsBuilder_.getMessage(index);
        }
      }
      public Builder setSendorsOnLeftHosts(
          int index, org.jcjxb.wsn.service.proto.BasicDataType.SensorsOnHost value) {
        if (sendorsOnLeftHostsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSendorsOnLeftHostsIsMutable();
          sendorsOnLeftHosts_.set(index, value);
          onChanged();
        } else {
          sendorsOnLeftHostsBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setSendorsOnLeftHosts(
          int index, org.jcjxb.wsn.service.proto.BasicDataType.SensorsOnHost.Builder builderForValue) {
        if (sendorsOnLeftHostsBuilder_ == null) {
          ensureSendorsOnLeftHostsIsMutable();
          sendorsOnLeftHosts_.set(index, builderForValue.build());
          onChanged();
        } else {
          sendorsOnLeftHostsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addSendorsOnLeftHosts(org.jcjxb.wsn.service.proto.BasicDataType.SensorsOnHost value) {
        if (sendorsOnLeftHostsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSendorsOnLeftHostsIsMutable();
          sendorsOnLeftHosts_.add(value);
          onChanged();
        } else {
          sendorsOnLeftHostsBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addSendorsOnLeftHosts(
          int index, org.jcjxb.wsn.service.proto.BasicDataType.SensorsOnHost value) {
        if (sendorsOnLeftHostsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSendorsOnLeftHostsIsMutable();
          sendorsOnLeftHosts_.add(index, value);
          onChanged();
        } else {
          sendorsOnLeftHostsBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addSendorsOnLeftHosts(
          org.jcjxb.wsn.service.proto.BasicDataType.SensorsOnHost.Builder builderForValue) {
        if (sendorsOnLeftHostsBuilder_ == null) {
          ensureSendorsOnLeftHostsIsMutable();
          sendorsOnLeftHosts_.add(builderForValue.build());
          onChanged();
        } else {
          sendorsOnLeftHostsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addSendorsOnLeftHosts(
          int index, org.jcjxb.wsn.service.proto.BasicDataType.SensorsOnHost.Builder builderForValue) {
        if (sendorsOnLeftHostsBuilder_ == null) {
          ensureSendorsOnLeftHostsIsMutable();
          sendorsOnLeftHosts_.add(index, builderForValue.build());
          onChanged();
        } else {
          sendorsOnLeftHostsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllSendorsOnLeftHosts(
          java.lang.Iterable<? extends org.jcjxb.wsn.service.proto.BasicDataType.SensorsOnHost> values) {
        if (sendorsOnLeftHostsBuilder_ == null) {
          ensureSendorsOnLeftHostsIsMutable();
          super.addAll(values, sendorsOnLeftHosts_);
          onChanged();
        } else {
          sendorsOnLeftHostsBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearSendorsOnLeftHosts() {
        if (sendorsOnLeftHostsBuilder_ == null) {
          sendorsOnLeftHosts_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          sendorsOnLeftHostsBuilder_.clear();
        }
        return this;
      }
      public Builder removeSendorsOnLeftHosts(int index) {
        if (sendorsOnLeftHostsBuilder_ == null) {
          ensureSendorsOnLeftHostsIsMutable();
          sendorsOnLeftHosts_.remove(index);
          onChanged();
        } else {
          sendorsOnLeftHostsBuilder_.remove(index);
        }
        return this;
      }
      public org.jcjxb.wsn.service.proto.BasicDataType.SensorsOnHost.Builder getSendorsOnLeftHostsBuilder(
          int index) {
        return getSendorsOnLeftHostsFieldBuilder().getBuilder(index);
      }
      public org.jcjxb.wsn.service.proto.BasicDataType.SensorsOnHostOrBuilder getSendorsOnLeftHostsOrBuilder(
          int index) {
        if (sendorsOnLeftHostsBuilder_ == null) {
          return sendorsOnLeftHosts_.get(index);  } else {
          return sendorsOnLeftHostsBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends org.jcjxb.wsn.service.proto.BasicDataType.SensorsOnHostOrBuilder> 
           getSendorsOnLeftHostsOrBuilderList() {
        if (sendorsOnLeftHostsBuilder_ != null) {
          return sendorsOnLeftHostsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(sendorsOnLeftHosts_);
        }
      }
      public org.jcjxb.wsn.service.proto.BasicDataType.SensorsOnHost.Builder addSendorsOnLeftHostsBuilder() {
        return getSendorsOnLeftHostsFieldBuilder().addBuilder(
            org.jcjxb.wsn.service.proto.BasicDataType.SensorsOnHost.getDefaultInstance());
      }
      public org.jcjxb.wsn.service.proto.BasicDataType.SensorsOnHost.Builder addSendorsOnLeftHostsBuilder(
          int index) {
        return getSendorsOnLeftHostsFieldBuilder().addBuilder(
            index, org.jcjxb.wsn.service.proto.BasicDataType.SensorsOnHost.getDefaultInstance());
      }
      public java.util.List<org.jcjxb.wsn.service.proto.BasicDataType.SensorsOnHost.Builder> 
           getSendorsOnLeftHostsBuilderList() {
        return getSendorsOnLeftHostsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          org.jcjxb.wsn.service.proto.BasicDataType.SensorsOnHost, org.jcjxb.wsn.service.proto.BasicDataType.SensorsOnHost.Builder, org.jcjxb.wsn.service.proto.BasicDataType.SensorsOnHostOrBuilder> 
          getSendorsOnLeftHostsFieldBuilder() {
        if (sendorsOnLeftHostsBuilder_ == null) {
          sendorsOnLeftHostsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              org.jcjxb.wsn.service.proto.BasicDataType.SensorsOnHost, org.jcjxb.wsn.service.proto.BasicDataType.SensorsOnHost.Builder, org.jcjxb.wsn.service.proto.BasicDataType.SensorsOnHostOrBuilder>(
                  sendorsOnLeftHosts_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          sendorsOnLeftHosts_ = null;
        }
        return sendorsOnLeftHostsBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:org.jcjxb.wsn.service.InitSimCmd)
    }
    
    static {
      defaultInstance = new InitSimCmd(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:org.jcjxb.wsn.service.InitSimCmd)
  }
  
  public static abstract class SService
      implements com.google.protobuf.Service {
    protected SService() {}
    
    public interface Interface {
    }
    
    public static com.google.protobuf.Service newReflectiveService(
        final Interface impl) {
      return new SService() {
      };
    }
    
    public static com.google.protobuf.BlockingService
        newReflectiveBlockingService(final BlockingInterface impl) {
      return new com.google.protobuf.BlockingService() {
        public final com.google.protobuf.Descriptors.ServiceDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }
        
        public final com.google.protobuf.Message callBlockingMethod(
            com.google.protobuf.Descriptors.MethodDescriptor method,
            com.google.protobuf.RpcController controller,
            com.google.protobuf.Message request)
            throws com.google.protobuf.ServiceException {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.callBlockingMethod() given method descriptor for " +
              "wrong service type.");
          }
          switch(method.getIndex()) {
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }
        
        public final com.google.protobuf.Message
            getRequestPrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getRequestPrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }
        
        public final com.google.protobuf.Message
            getResponsePrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getResponsePrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }
        
      };
    }
    
    public static final
        com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptor() {
      return org.jcjxb.wsn.service.proto.SlaveService.getDescriptor().getServices().get(0);
    }
    public final com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    
    public final void callMethod(
        com.google.protobuf.Descriptors.MethodDescriptor method,
        com.google.protobuf.RpcController controller,
        com.google.protobuf.Message request,
        com.google.protobuf.RpcCallback<
          com.google.protobuf.Message> done) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.callMethod() given method descriptor for wrong " +
          "service type.");
      }
      switch(method.getIndex()) {
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }
    
    public final com.google.protobuf.Message
        getRequestPrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getRequestPrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }
    
    public final com.google.protobuf.Message
        getResponsePrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getResponsePrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }
    
    public static Stub newStub(
        com.google.protobuf.RpcChannel channel) {
      return new Stub(channel);
    }
    
    public static final class Stub extends org.jcjxb.wsn.service.proto.SlaveService.SService implements Interface {
      private Stub(com.google.protobuf.RpcChannel channel) {
        this.channel = channel;
      }
      
      private final com.google.protobuf.RpcChannel channel;
      
      public com.google.protobuf.RpcChannel getChannel() {
        return channel;
      }
    }
    
    public static BlockingInterface newBlockingStub(
        com.google.protobuf.BlockingRpcChannel channel) {
      return new BlockingStub(channel);
    }
    
    public interface BlockingInterface {}
    
    private static final class BlockingStub implements BlockingInterface {
      private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
        this.channel = channel;
      }
      
      private final com.google.protobuf.BlockingRpcChannel channel;
    }
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_jcjxb_wsn_service_InitSimCmd_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_jcjxb_wsn_service_InitSimCmd_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022SlaveService.proto\022\025org.jcjxb.wsn.serv" +
      "ice\032\023BasicDataType.proto\"\217\001\n\nInitSimCmd\022" +
      "?\n\021sendorsOnThisHost\030\001 \001(\0132$.org.jcjxb.w" +
      "sn.service.SensorsOnHost\022@\n\022sendorsOnLef" +
      "tHosts\030\002 \003(\0132$.org.jcjxb.wsn.service.Sen" +
      "sorsOnHost2\n\n\010SServiceB.\n\033org.jcjxb.wsn." +
      "service.protoB\014SlaveService\210\001\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_org_jcjxb_wsn_service_InitSimCmd_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_org_jcjxb_wsn_service_InitSimCmd_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_jcjxb_wsn_service_InitSimCmd_descriptor,
              new java.lang.String[] { "SendorsOnThisHost", "SendorsOnLeftHosts", },
              org.jcjxb.wsn.service.proto.SlaveService.InitSimCmd.class,
              org.jcjxb.wsn.service.proto.SlaveService.InitSimCmd.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.jcjxb.wsn.service.proto.BasicDataType.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
