// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SlaveService.proto

package org.jcjxb.wsn.service.proto;

public final class SlaveService {
  private SlaveService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ExecRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional int64 globalVirtualTime = 1;
    boolean hasGlobalVirtualTime();
    long getGlobalVirtualTime();
  }
  public static final class ExecRequest extends
      com.google.protobuf.GeneratedMessage
      implements ExecRequestOrBuilder {
    // Use ExecRequest.newBuilder() to construct.
    private ExecRequest(Builder builder) {
      super(builder);
    }
    private ExecRequest(boolean noInit) {}
    
    private static final ExecRequest defaultInstance;
    public static ExecRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public ExecRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.jcjxb.wsn.service.proto.SlaveService.internal_static_org_jcjxb_wsn_service_ExecRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.jcjxb.wsn.service.proto.SlaveService.internal_static_org_jcjxb_wsn_service_ExecRequest_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional int64 globalVirtualTime = 1;
    public static final int GLOBALVIRTUALTIME_FIELD_NUMBER = 1;
    private long globalVirtualTime_;
    public boolean hasGlobalVirtualTime() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public long getGlobalVirtualTime() {
      return globalVirtualTime_;
    }
    
    private void initFields() {
      globalVirtualTime_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, globalVirtualTime_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, globalVirtualTime_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.jcjxb.wsn.service.proto.SlaveService.ExecRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.jcjxb.wsn.service.proto.SlaveService.ExecRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.jcjxb.wsn.service.proto.SlaveService.ExecRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.jcjxb.wsn.service.proto.SlaveService.ExecRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.jcjxb.wsn.service.proto.SlaveService.ExecRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.jcjxb.wsn.service.proto.SlaveService.ExecRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.jcjxb.wsn.service.proto.SlaveService.ExecRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.jcjxb.wsn.service.proto.SlaveService.ExecRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.jcjxb.wsn.service.proto.SlaveService.ExecRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.jcjxb.wsn.service.proto.SlaveService.ExecRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.jcjxb.wsn.service.proto.SlaveService.ExecRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.jcjxb.wsn.service.proto.SlaveService.ExecRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.jcjxb.wsn.service.proto.SlaveService.internal_static_org_jcjxb_wsn_service_ExecRequest_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.jcjxb.wsn.service.proto.SlaveService.internal_static_org_jcjxb_wsn_service_ExecRequest_fieldAccessorTable;
      }
      
      // Construct using org.jcjxb.wsn.service.proto.SlaveService.ExecRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        globalVirtualTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.jcjxb.wsn.service.proto.SlaveService.ExecRequest.getDescriptor();
      }
      
      public org.jcjxb.wsn.service.proto.SlaveService.ExecRequest getDefaultInstanceForType() {
        return org.jcjxb.wsn.service.proto.SlaveService.ExecRequest.getDefaultInstance();
      }
      
      public org.jcjxb.wsn.service.proto.SlaveService.ExecRequest build() {
        org.jcjxb.wsn.service.proto.SlaveService.ExecRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.jcjxb.wsn.service.proto.SlaveService.ExecRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.jcjxb.wsn.service.proto.SlaveService.ExecRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.jcjxb.wsn.service.proto.SlaveService.ExecRequest buildPartial() {
        org.jcjxb.wsn.service.proto.SlaveService.ExecRequest result = new org.jcjxb.wsn.service.proto.SlaveService.ExecRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.globalVirtualTime_ = globalVirtualTime_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.jcjxb.wsn.service.proto.SlaveService.ExecRequest) {
          return mergeFrom((org.jcjxb.wsn.service.proto.SlaveService.ExecRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.jcjxb.wsn.service.proto.SlaveService.ExecRequest other) {
        if (other == org.jcjxb.wsn.service.proto.SlaveService.ExecRequest.getDefaultInstance()) return this;
        if (other.hasGlobalVirtualTime()) {
          setGlobalVirtualTime(other.getGlobalVirtualTime());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              globalVirtualTime_ = input.readInt64();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional int64 globalVirtualTime = 1;
      private long globalVirtualTime_ ;
      public boolean hasGlobalVirtualTime() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public long getGlobalVirtualTime() {
        return globalVirtualTime_;
      }
      public Builder setGlobalVirtualTime(long value) {
        bitField0_ |= 0x00000001;
        globalVirtualTime_ = value;
        onChanged();
        return this;
      }
      public Builder clearGlobalVirtualTime() {
        bitField0_ = (bitField0_ & ~0x00000001);
        globalVirtualTime_ = 0L;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:org.jcjxb.wsn.service.ExecRequest)
    }
    
    static {
      defaultInstance = new ExecRequest(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:org.jcjxb.wsn.service.ExecRequest)
  }
  
  public interface LVTSyncOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional int32 slaveId = 1;
    boolean hasSlaveId();
    int getSlaveId();
    
    // optional int64 localTime = 2;
    boolean hasLocalTime();
    long getLocalTime();
    
    // repeated .org.jcjxb.wsn.service.LVTSync.Update update = 3;
    java.util.List<org.jcjxb.wsn.service.proto.SlaveService.LVTSync.Update> 
        getUpdateList();
    org.jcjxb.wsn.service.proto.SlaveService.LVTSync.Update getUpdate(int index);
    int getUpdateCount();
    java.util.List<? extends org.jcjxb.wsn.service.proto.SlaveService.LVTSync.UpdateOrBuilder> 
        getUpdateOrBuilderList();
    org.jcjxb.wsn.service.proto.SlaveService.LVTSync.UpdateOrBuilder getUpdateOrBuilder(
        int index);
  }
  public static final class LVTSync extends
      com.google.protobuf.GeneratedMessage
      implements LVTSyncOrBuilder {
    // Use LVTSync.newBuilder() to construct.
    private LVTSync(Builder builder) {
      super(builder);
    }
    private LVTSync(boolean noInit) {}
    
    private static final LVTSync defaultInstance;
    public static LVTSync getDefaultInstance() {
      return defaultInstance;
    }
    
    public LVTSync getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.jcjxb.wsn.service.proto.SlaveService.internal_static_org_jcjxb_wsn_service_LVTSync_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.jcjxb.wsn.service.proto.SlaveService.internal_static_org_jcjxb_wsn_service_LVTSync_fieldAccessorTable;
    }
    
    public interface UpdateOrBuilder
        extends com.google.protobuf.MessageOrBuilder {
      
      // optional int32 slaveId = 1;
      boolean hasSlaveId();
      int getSlaveId();
      
      // optional int64 localTime = 2;
      boolean hasLocalTime();
      long getLocalTime();
    }
    public static final class Update extends
        com.google.protobuf.GeneratedMessage
        implements UpdateOrBuilder {
      // Use Update.newBuilder() to construct.
      private Update(Builder builder) {
        super(builder);
      }
      private Update(boolean noInit) {}
      
      private static final Update defaultInstance;
      public static Update getDefaultInstance() {
        return defaultInstance;
      }
      
      public Update getDefaultInstanceForType() {
        return defaultInstance;
      }
      
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.jcjxb.wsn.service.proto.SlaveService.internal_static_org_jcjxb_wsn_service_LVTSync_Update_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.jcjxb.wsn.service.proto.SlaveService.internal_static_org_jcjxb_wsn_service_LVTSync_Update_fieldAccessorTable;
      }
      
      private int bitField0_;
      // optional int32 slaveId = 1;
      public static final int SLAVEID_FIELD_NUMBER = 1;
      private int slaveId_;
      public boolean hasSlaveId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getSlaveId() {
        return slaveId_;
      }
      
      // optional int64 localTime = 2;
      public static final int LOCALTIME_FIELD_NUMBER = 2;
      private long localTime_;
      public boolean hasLocalTime() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public long getLocalTime() {
        return localTime_;
      }
      
      private void initFields() {
        slaveId_ = 0;
        localTime_ = 0L;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;
        
        memoizedIsInitialized = 1;
        return true;
      }
      
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeInt32(1, slaveId_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeInt64(2, localTime_);
        }
        getUnknownFields().writeTo(output);
      }
      
      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
      
        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(1, slaveId_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt64Size(2, localTime_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }
      
      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }
      
      public static org.jcjxb.wsn.service.proto.SlaveService.LVTSync.Update parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static org.jcjxb.wsn.service.proto.SlaveService.LVTSync.Update parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static org.jcjxb.wsn.service.proto.SlaveService.LVTSync.Update parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static org.jcjxb.wsn.service.proto.SlaveService.LVTSync.Update parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static org.jcjxb.wsn.service.proto.SlaveService.LVTSync.Update parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static org.jcjxb.wsn.service.proto.SlaveService.LVTSync.Update parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static org.jcjxb.wsn.service.proto.SlaveService.LVTSync.Update parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static org.jcjxb.wsn.service.proto.SlaveService.LVTSync.Update parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static org.jcjxb.wsn.service.proto.SlaveService.LVTSync.Update parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static org.jcjxb.wsn.service.proto.SlaveService.LVTSync.Update parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      
      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(org.jcjxb.wsn.service.proto.SlaveService.LVTSync.Update prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }
      
      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements org.jcjxb.wsn.service.proto.SlaveService.LVTSync.UpdateOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return org.jcjxb.wsn.service.proto.SlaveService.internal_static_org_jcjxb_wsn_service_LVTSync_Update_descriptor;
        }
        
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return org.jcjxb.wsn.service.proto.SlaveService.internal_static_org_jcjxb_wsn_service_LVTSync_Update_fieldAccessorTable;
        }
        
        // Construct using org.jcjxb.wsn.service.proto.SlaveService.LVTSync.Update.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }
        
        private Builder(BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }
        
        public Builder clear() {
          super.clear();
          slaveId_ = 0;
          bitField0_ = (bitField0_ & ~0x00000001);
          localTime_ = 0L;
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }
        
        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }
        
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return org.jcjxb.wsn.service.proto.SlaveService.LVTSync.Update.getDescriptor();
        }
        
        public org.jcjxb.wsn.service.proto.SlaveService.LVTSync.Update getDefaultInstanceForType() {
          return org.jcjxb.wsn.service.proto.SlaveService.LVTSync.Update.getDefaultInstance();
        }
        
        public org.jcjxb.wsn.service.proto.SlaveService.LVTSync.Update build() {
          org.jcjxb.wsn.service.proto.SlaveService.LVTSync.Update result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }
        
        private org.jcjxb.wsn.service.proto.SlaveService.LVTSync.Update buildParsed()
            throws com.google.protobuf.InvalidProtocolBufferException {
          org.jcjxb.wsn.service.proto.SlaveService.LVTSync.Update result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(
              result).asInvalidProtocolBufferException();
          }
          return result;
        }
        
        public org.jcjxb.wsn.service.proto.SlaveService.LVTSync.Update buildPartial() {
          org.jcjxb.wsn.service.proto.SlaveService.LVTSync.Update result = new org.jcjxb.wsn.service.proto.SlaveService.LVTSync.Update(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.slaveId_ = slaveId_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.localTime_ = localTime_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }
        
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof org.jcjxb.wsn.service.proto.SlaveService.LVTSync.Update) {
            return mergeFrom((org.jcjxb.wsn.service.proto.SlaveService.LVTSync.Update)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }
        
        public Builder mergeFrom(org.jcjxb.wsn.service.proto.SlaveService.LVTSync.Update other) {
          if (other == org.jcjxb.wsn.service.proto.SlaveService.LVTSync.Update.getDefaultInstance()) return this;
          if (other.hasSlaveId()) {
            setSlaveId(other.getSlaveId());
          }
          if (other.hasLocalTime()) {
            setLocalTime(other.getLocalTime());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }
        
        public final boolean isInitialized() {
          return true;
        }
        
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder(
              this.getUnknownFields());
          while (true) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  this.setUnknownFields(unknownFields.build());
                  onChanged();
                  return this;
                }
                break;
              }
              case 8: {
                bitField0_ |= 0x00000001;
                slaveId_ = input.readInt32();
                break;
              }
              case 16: {
                bitField0_ |= 0x00000002;
                localTime_ = input.readInt64();
                break;
              }
            }
          }
        }
        
        private int bitField0_;
        
        // optional int32 slaveId = 1;
        private int slaveId_ ;
        public boolean hasSlaveId() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        public int getSlaveId() {
          return slaveId_;
        }
        public Builder setSlaveId(int value) {
          bitField0_ |= 0x00000001;
          slaveId_ = value;
          onChanged();
          return this;
        }
        public Builder clearSlaveId() {
          bitField0_ = (bitField0_ & ~0x00000001);
          slaveId_ = 0;
          onChanged();
          return this;
        }
        
        // optional int64 localTime = 2;
        private long localTime_ ;
        public boolean hasLocalTime() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        public long getLocalTime() {
          return localTime_;
        }
        public Builder setLocalTime(long value) {
          bitField0_ |= 0x00000002;
          localTime_ = value;
          onChanged();
          return this;
        }
        public Builder clearLocalTime() {
          bitField0_ = (bitField0_ & ~0x00000002);
          localTime_ = 0L;
          onChanged();
          return this;
        }
        
        // @@protoc_insertion_point(builder_scope:org.jcjxb.wsn.service.LVTSync.Update)
      }
      
      static {
        defaultInstance = new Update(true);
        defaultInstance.initFields();
      }
      
      // @@protoc_insertion_point(class_scope:org.jcjxb.wsn.service.LVTSync.Update)
    }
    
    private int bitField0_;
    // optional int32 slaveId = 1;
    public static final int SLAVEID_FIELD_NUMBER = 1;
    private int slaveId_;
    public boolean hasSlaveId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getSlaveId() {
      return slaveId_;
    }
    
    // optional int64 localTime = 2;
    public static final int LOCALTIME_FIELD_NUMBER = 2;
    private long localTime_;
    public boolean hasLocalTime() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public long getLocalTime() {
      return localTime_;
    }
    
    // repeated .org.jcjxb.wsn.service.LVTSync.Update update = 3;
    public static final int UPDATE_FIELD_NUMBER = 3;
    private java.util.List<org.jcjxb.wsn.service.proto.SlaveService.LVTSync.Update> update_;
    public java.util.List<org.jcjxb.wsn.service.proto.SlaveService.LVTSync.Update> getUpdateList() {
      return update_;
    }
    public java.util.List<? extends org.jcjxb.wsn.service.proto.SlaveService.LVTSync.UpdateOrBuilder> 
        getUpdateOrBuilderList() {
      return update_;
    }
    public int getUpdateCount() {
      return update_.size();
    }
    public org.jcjxb.wsn.service.proto.SlaveService.LVTSync.Update getUpdate(int index) {
      return update_.get(index);
    }
    public org.jcjxb.wsn.service.proto.SlaveService.LVTSync.UpdateOrBuilder getUpdateOrBuilder(
        int index) {
      return update_.get(index);
    }
    
    private void initFields() {
      slaveId_ = 0;
      localTime_ = 0L;
      update_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, slaveId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, localTime_);
      }
      for (int i = 0; i < update_.size(); i++) {
        output.writeMessage(3, update_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, slaveId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, localTime_);
      }
      for (int i = 0; i < update_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, update_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.jcjxb.wsn.service.proto.SlaveService.LVTSync parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.jcjxb.wsn.service.proto.SlaveService.LVTSync parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.jcjxb.wsn.service.proto.SlaveService.LVTSync parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.jcjxb.wsn.service.proto.SlaveService.LVTSync parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.jcjxb.wsn.service.proto.SlaveService.LVTSync parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.jcjxb.wsn.service.proto.SlaveService.LVTSync parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.jcjxb.wsn.service.proto.SlaveService.LVTSync parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.jcjxb.wsn.service.proto.SlaveService.LVTSync parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.jcjxb.wsn.service.proto.SlaveService.LVTSync parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.jcjxb.wsn.service.proto.SlaveService.LVTSync parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.jcjxb.wsn.service.proto.SlaveService.LVTSync prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.jcjxb.wsn.service.proto.SlaveService.LVTSyncOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.jcjxb.wsn.service.proto.SlaveService.internal_static_org_jcjxb_wsn_service_LVTSync_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.jcjxb.wsn.service.proto.SlaveService.internal_static_org_jcjxb_wsn_service_LVTSync_fieldAccessorTable;
      }
      
      // Construct using org.jcjxb.wsn.service.proto.SlaveService.LVTSync.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getUpdateFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        slaveId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        localTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        if (updateBuilder_ == null) {
          update_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          updateBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.jcjxb.wsn.service.proto.SlaveService.LVTSync.getDescriptor();
      }
      
      public org.jcjxb.wsn.service.proto.SlaveService.LVTSync getDefaultInstanceForType() {
        return org.jcjxb.wsn.service.proto.SlaveService.LVTSync.getDefaultInstance();
      }
      
      public org.jcjxb.wsn.service.proto.SlaveService.LVTSync build() {
        org.jcjxb.wsn.service.proto.SlaveService.LVTSync result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.jcjxb.wsn.service.proto.SlaveService.LVTSync buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.jcjxb.wsn.service.proto.SlaveService.LVTSync result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.jcjxb.wsn.service.proto.SlaveService.LVTSync buildPartial() {
        org.jcjxb.wsn.service.proto.SlaveService.LVTSync result = new org.jcjxb.wsn.service.proto.SlaveService.LVTSync(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.slaveId_ = slaveId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.localTime_ = localTime_;
        if (updateBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            update_ = java.util.Collections.unmodifiableList(update_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.update_ = update_;
        } else {
          result.update_ = updateBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.jcjxb.wsn.service.proto.SlaveService.LVTSync) {
          return mergeFrom((org.jcjxb.wsn.service.proto.SlaveService.LVTSync)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.jcjxb.wsn.service.proto.SlaveService.LVTSync other) {
        if (other == org.jcjxb.wsn.service.proto.SlaveService.LVTSync.getDefaultInstance()) return this;
        if (other.hasSlaveId()) {
          setSlaveId(other.getSlaveId());
        }
        if (other.hasLocalTime()) {
          setLocalTime(other.getLocalTime());
        }
        if (updateBuilder_ == null) {
          if (!other.update_.isEmpty()) {
            if (update_.isEmpty()) {
              update_ = other.update_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureUpdateIsMutable();
              update_.addAll(other.update_);
            }
            onChanged();
          }
        } else {
          if (!other.update_.isEmpty()) {
            if (updateBuilder_.isEmpty()) {
              updateBuilder_.dispose();
              updateBuilder_ = null;
              update_ = other.update_;
              bitField0_ = (bitField0_ & ~0x00000004);
              updateBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getUpdateFieldBuilder() : null;
            } else {
              updateBuilder_.addAllMessages(other.update_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              slaveId_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              localTime_ = input.readInt64();
              break;
            }
            case 26: {
              org.jcjxb.wsn.service.proto.SlaveService.LVTSync.Update.Builder subBuilder = org.jcjxb.wsn.service.proto.SlaveService.LVTSync.Update.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addUpdate(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional int32 slaveId = 1;
      private int slaveId_ ;
      public boolean hasSlaveId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getSlaveId() {
        return slaveId_;
      }
      public Builder setSlaveId(int value) {
        bitField0_ |= 0x00000001;
        slaveId_ = value;
        onChanged();
        return this;
      }
      public Builder clearSlaveId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        slaveId_ = 0;
        onChanged();
        return this;
      }
      
      // optional int64 localTime = 2;
      private long localTime_ ;
      public boolean hasLocalTime() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public long getLocalTime() {
        return localTime_;
      }
      public Builder setLocalTime(long value) {
        bitField0_ |= 0x00000002;
        localTime_ = value;
        onChanged();
        return this;
      }
      public Builder clearLocalTime() {
        bitField0_ = (bitField0_ & ~0x00000002);
        localTime_ = 0L;
        onChanged();
        return this;
      }
      
      // repeated .org.jcjxb.wsn.service.LVTSync.Update update = 3;
      private java.util.List<org.jcjxb.wsn.service.proto.SlaveService.LVTSync.Update> update_ =
        java.util.Collections.emptyList();
      private void ensureUpdateIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          update_ = new java.util.ArrayList<org.jcjxb.wsn.service.proto.SlaveService.LVTSync.Update>(update_);
          bitField0_ |= 0x00000004;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          org.jcjxb.wsn.service.proto.SlaveService.LVTSync.Update, org.jcjxb.wsn.service.proto.SlaveService.LVTSync.Update.Builder, org.jcjxb.wsn.service.proto.SlaveService.LVTSync.UpdateOrBuilder> updateBuilder_;
      
      public java.util.List<org.jcjxb.wsn.service.proto.SlaveService.LVTSync.Update> getUpdateList() {
        if (updateBuilder_ == null) {
          return java.util.Collections.unmodifiableList(update_);
        } else {
          return updateBuilder_.getMessageList();
        }
      }
      public int getUpdateCount() {
        if (updateBuilder_ == null) {
          return update_.size();
        } else {
          return updateBuilder_.getCount();
        }
      }
      public org.jcjxb.wsn.service.proto.SlaveService.LVTSync.Update getUpdate(int index) {
        if (updateBuilder_ == null) {
          return update_.get(index);
        } else {
          return updateBuilder_.getMessage(index);
        }
      }
      public Builder setUpdate(
          int index, org.jcjxb.wsn.service.proto.SlaveService.LVTSync.Update value) {
        if (updateBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUpdateIsMutable();
          update_.set(index, value);
          onChanged();
        } else {
          updateBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setUpdate(
          int index, org.jcjxb.wsn.service.proto.SlaveService.LVTSync.Update.Builder builderForValue) {
        if (updateBuilder_ == null) {
          ensureUpdateIsMutable();
          update_.set(index, builderForValue.build());
          onChanged();
        } else {
          updateBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addUpdate(org.jcjxb.wsn.service.proto.SlaveService.LVTSync.Update value) {
        if (updateBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUpdateIsMutable();
          update_.add(value);
          onChanged();
        } else {
          updateBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addUpdate(
          int index, org.jcjxb.wsn.service.proto.SlaveService.LVTSync.Update value) {
        if (updateBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUpdateIsMutable();
          update_.add(index, value);
          onChanged();
        } else {
          updateBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addUpdate(
          org.jcjxb.wsn.service.proto.SlaveService.LVTSync.Update.Builder builderForValue) {
        if (updateBuilder_ == null) {
          ensureUpdateIsMutable();
          update_.add(builderForValue.build());
          onChanged();
        } else {
          updateBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addUpdate(
          int index, org.jcjxb.wsn.service.proto.SlaveService.LVTSync.Update.Builder builderForValue) {
        if (updateBuilder_ == null) {
          ensureUpdateIsMutable();
          update_.add(index, builderForValue.build());
          onChanged();
        } else {
          updateBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllUpdate(
          java.lang.Iterable<? extends org.jcjxb.wsn.service.proto.SlaveService.LVTSync.Update> values) {
        if (updateBuilder_ == null) {
          ensureUpdateIsMutable();
          super.addAll(values, update_);
          onChanged();
        } else {
          updateBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearUpdate() {
        if (updateBuilder_ == null) {
          update_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          updateBuilder_.clear();
        }
        return this;
      }
      public Builder removeUpdate(int index) {
        if (updateBuilder_ == null) {
          ensureUpdateIsMutable();
          update_.remove(index);
          onChanged();
        } else {
          updateBuilder_.remove(index);
        }
        return this;
      }
      public org.jcjxb.wsn.service.proto.SlaveService.LVTSync.Update.Builder getUpdateBuilder(
          int index) {
        return getUpdateFieldBuilder().getBuilder(index);
      }
      public org.jcjxb.wsn.service.proto.SlaveService.LVTSync.UpdateOrBuilder getUpdateOrBuilder(
          int index) {
        if (updateBuilder_ == null) {
          return update_.get(index);  } else {
          return updateBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends org.jcjxb.wsn.service.proto.SlaveService.LVTSync.UpdateOrBuilder> 
           getUpdateOrBuilderList() {
        if (updateBuilder_ != null) {
          return updateBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(update_);
        }
      }
      public org.jcjxb.wsn.service.proto.SlaveService.LVTSync.Update.Builder addUpdateBuilder() {
        return getUpdateFieldBuilder().addBuilder(
            org.jcjxb.wsn.service.proto.SlaveService.LVTSync.Update.getDefaultInstance());
      }
      public org.jcjxb.wsn.service.proto.SlaveService.LVTSync.Update.Builder addUpdateBuilder(
          int index) {
        return getUpdateFieldBuilder().addBuilder(
            index, org.jcjxb.wsn.service.proto.SlaveService.LVTSync.Update.getDefaultInstance());
      }
      public java.util.List<org.jcjxb.wsn.service.proto.SlaveService.LVTSync.Update.Builder> 
           getUpdateBuilderList() {
        return getUpdateFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          org.jcjxb.wsn.service.proto.SlaveService.LVTSync.Update, org.jcjxb.wsn.service.proto.SlaveService.LVTSync.Update.Builder, org.jcjxb.wsn.service.proto.SlaveService.LVTSync.UpdateOrBuilder> 
          getUpdateFieldBuilder() {
        if (updateBuilder_ == null) {
          updateBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              org.jcjxb.wsn.service.proto.SlaveService.LVTSync.Update, org.jcjxb.wsn.service.proto.SlaveService.LVTSync.Update.Builder, org.jcjxb.wsn.service.proto.SlaveService.LVTSync.UpdateOrBuilder>(
                  update_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          update_ = null;
        }
        return updateBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:org.jcjxb.wsn.service.LVTSync)
    }
    
    static {
      defaultInstance = new LVTSync(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:org.jcjxb.wsn.service.LVTSync)
  }
  
  public interface EventsRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated .org.jcjxb.wsn.service.Event event = 1;
    java.util.List<org.jcjxb.wsn.service.proto.BasicDataType.Event> 
        getEventList();
    org.jcjxb.wsn.service.proto.BasicDataType.Event getEvent(int index);
    int getEventCount();
    java.util.List<? extends org.jcjxb.wsn.service.proto.BasicDataType.EventOrBuilder> 
        getEventOrBuilderList();
    org.jcjxb.wsn.service.proto.BasicDataType.EventOrBuilder getEventOrBuilder(
        int index);
  }
  public static final class EventsRequest extends
      com.google.protobuf.GeneratedMessage
      implements EventsRequestOrBuilder {
    // Use EventsRequest.newBuilder() to construct.
    private EventsRequest(Builder builder) {
      super(builder);
    }
    private EventsRequest(boolean noInit) {}
    
    private static final EventsRequest defaultInstance;
    public static EventsRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public EventsRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.jcjxb.wsn.service.proto.SlaveService.internal_static_org_jcjxb_wsn_service_EventsRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.jcjxb.wsn.service.proto.SlaveService.internal_static_org_jcjxb_wsn_service_EventsRequest_fieldAccessorTable;
    }
    
    // repeated .org.jcjxb.wsn.service.Event event = 1;
    public static final int EVENT_FIELD_NUMBER = 1;
    private java.util.List<org.jcjxb.wsn.service.proto.BasicDataType.Event> event_;
    public java.util.List<org.jcjxb.wsn.service.proto.BasicDataType.Event> getEventList() {
      return event_;
    }
    public java.util.List<? extends org.jcjxb.wsn.service.proto.BasicDataType.EventOrBuilder> 
        getEventOrBuilderList() {
      return event_;
    }
    public int getEventCount() {
      return event_.size();
    }
    public org.jcjxb.wsn.service.proto.BasicDataType.Event getEvent(int index) {
      return event_.get(index);
    }
    public org.jcjxb.wsn.service.proto.BasicDataType.EventOrBuilder getEventOrBuilder(
        int index) {
      return event_.get(index);
    }
    
    private void initFields() {
      event_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < event_.size(); i++) {
        output.writeMessage(1, event_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (int i = 0; i < event_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, event_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.jcjxb.wsn.service.proto.SlaveService.EventsRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.jcjxb.wsn.service.proto.SlaveService.EventsRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.jcjxb.wsn.service.proto.SlaveService.EventsRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.jcjxb.wsn.service.proto.SlaveService.EventsRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.jcjxb.wsn.service.proto.SlaveService.EventsRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.jcjxb.wsn.service.proto.SlaveService.EventsRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.jcjxb.wsn.service.proto.SlaveService.EventsRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.jcjxb.wsn.service.proto.SlaveService.EventsRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.jcjxb.wsn.service.proto.SlaveService.EventsRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.jcjxb.wsn.service.proto.SlaveService.EventsRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.jcjxb.wsn.service.proto.SlaveService.EventsRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.jcjxb.wsn.service.proto.SlaveService.EventsRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.jcjxb.wsn.service.proto.SlaveService.internal_static_org_jcjxb_wsn_service_EventsRequest_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.jcjxb.wsn.service.proto.SlaveService.internal_static_org_jcjxb_wsn_service_EventsRequest_fieldAccessorTable;
      }
      
      // Construct using org.jcjxb.wsn.service.proto.SlaveService.EventsRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getEventFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (eventBuilder_ == null) {
          event_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          eventBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.jcjxb.wsn.service.proto.SlaveService.EventsRequest.getDescriptor();
      }
      
      public org.jcjxb.wsn.service.proto.SlaveService.EventsRequest getDefaultInstanceForType() {
        return org.jcjxb.wsn.service.proto.SlaveService.EventsRequest.getDefaultInstance();
      }
      
      public org.jcjxb.wsn.service.proto.SlaveService.EventsRequest build() {
        org.jcjxb.wsn.service.proto.SlaveService.EventsRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.jcjxb.wsn.service.proto.SlaveService.EventsRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.jcjxb.wsn.service.proto.SlaveService.EventsRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.jcjxb.wsn.service.proto.SlaveService.EventsRequest buildPartial() {
        org.jcjxb.wsn.service.proto.SlaveService.EventsRequest result = new org.jcjxb.wsn.service.proto.SlaveService.EventsRequest(this);
        int from_bitField0_ = bitField0_;
        if (eventBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            event_ = java.util.Collections.unmodifiableList(event_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.event_ = event_;
        } else {
          result.event_ = eventBuilder_.build();
        }
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.jcjxb.wsn.service.proto.SlaveService.EventsRequest) {
          return mergeFrom((org.jcjxb.wsn.service.proto.SlaveService.EventsRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.jcjxb.wsn.service.proto.SlaveService.EventsRequest other) {
        if (other == org.jcjxb.wsn.service.proto.SlaveService.EventsRequest.getDefaultInstance()) return this;
        if (eventBuilder_ == null) {
          if (!other.event_.isEmpty()) {
            if (event_.isEmpty()) {
              event_ = other.event_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureEventIsMutable();
              event_.addAll(other.event_);
            }
            onChanged();
          }
        } else {
          if (!other.event_.isEmpty()) {
            if (eventBuilder_.isEmpty()) {
              eventBuilder_.dispose();
              eventBuilder_ = null;
              event_ = other.event_;
              bitField0_ = (bitField0_ & ~0x00000001);
              eventBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getEventFieldBuilder() : null;
            } else {
              eventBuilder_.addAllMessages(other.event_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              org.jcjxb.wsn.service.proto.BasicDataType.Event.Builder subBuilder = org.jcjxb.wsn.service.proto.BasicDataType.Event.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addEvent(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated .org.jcjxb.wsn.service.Event event = 1;
      private java.util.List<org.jcjxb.wsn.service.proto.BasicDataType.Event> event_ =
        java.util.Collections.emptyList();
      private void ensureEventIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          event_ = new java.util.ArrayList<org.jcjxb.wsn.service.proto.BasicDataType.Event>(event_);
          bitField0_ |= 0x00000001;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          org.jcjxb.wsn.service.proto.BasicDataType.Event, org.jcjxb.wsn.service.proto.BasicDataType.Event.Builder, org.jcjxb.wsn.service.proto.BasicDataType.EventOrBuilder> eventBuilder_;
      
      public java.util.List<org.jcjxb.wsn.service.proto.BasicDataType.Event> getEventList() {
        if (eventBuilder_ == null) {
          return java.util.Collections.unmodifiableList(event_);
        } else {
          return eventBuilder_.getMessageList();
        }
      }
      public int getEventCount() {
        if (eventBuilder_ == null) {
          return event_.size();
        } else {
          return eventBuilder_.getCount();
        }
      }
      public org.jcjxb.wsn.service.proto.BasicDataType.Event getEvent(int index) {
        if (eventBuilder_ == null) {
          return event_.get(index);
        } else {
          return eventBuilder_.getMessage(index);
        }
      }
      public Builder setEvent(
          int index, org.jcjxb.wsn.service.proto.BasicDataType.Event value) {
        if (eventBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEventIsMutable();
          event_.set(index, value);
          onChanged();
        } else {
          eventBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setEvent(
          int index, org.jcjxb.wsn.service.proto.BasicDataType.Event.Builder builderForValue) {
        if (eventBuilder_ == null) {
          ensureEventIsMutable();
          event_.set(index, builderForValue.build());
          onChanged();
        } else {
          eventBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addEvent(org.jcjxb.wsn.service.proto.BasicDataType.Event value) {
        if (eventBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEventIsMutable();
          event_.add(value);
          onChanged();
        } else {
          eventBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addEvent(
          int index, org.jcjxb.wsn.service.proto.BasicDataType.Event value) {
        if (eventBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEventIsMutable();
          event_.add(index, value);
          onChanged();
        } else {
          eventBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addEvent(
          org.jcjxb.wsn.service.proto.BasicDataType.Event.Builder builderForValue) {
        if (eventBuilder_ == null) {
          ensureEventIsMutable();
          event_.add(builderForValue.build());
          onChanged();
        } else {
          eventBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addEvent(
          int index, org.jcjxb.wsn.service.proto.BasicDataType.Event.Builder builderForValue) {
        if (eventBuilder_ == null) {
          ensureEventIsMutable();
          event_.add(index, builderForValue.build());
          onChanged();
        } else {
          eventBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllEvent(
          java.lang.Iterable<? extends org.jcjxb.wsn.service.proto.BasicDataType.Event> values) {
        if (eventBuilder_ == null) {
          ensureEventIsMutable();
          super.addAll(values, event_);
          onChanged();
        } else {
          eventBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearEvent() {
        if (eventBuilder_ == null) {
          event_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          eventBuilder_.clear();
        }
        return this;
      }
      public Builder removeEvent(int index) {
        if (eventBuilder_ == null) {
          ensureEventIsMutable();
          event_.remove(index);
          onChanged();
        } else {
          eventBuilder_.remove(index);
        }
        return this;
      }
      public org.jcjxb.wsn.service.proto.BasicDataType.Event.Builder getEventBuilder(
          int index) {
        return getEventFieldBuilder().getBuilder(index);
      }
      public org.jcjxb.wsn.service.proto.BasicDataType.EventOrBuilder getEventOrBuilder(
          int index) {
        if (eventBuilder_ == null) {
          return event_.get(index);  } else {
          return eventBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends org.jcjxb.wsn.service.proto.BasicDataType.EventOrBuilder> 
           getEventOrBuilderList() {
        if (eventBuilder_ != null) {
          return eventBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(event_);
        }
      }
      public org.jcjxb.wsn.service.proto.BasicDataType.Event.Builder addEventBuilder() {
        return getEventFieldBuilder().addBuilder(
            org.jcjxb.wsn.service.proto.BasicDataType.Event.getDefaultInstance());
      }
      public org.jcjxb.wsn.service.proto.BasicDataType.Event.Builder addEventBuilder(
          int index) {
        return getEventFieldBuilder().addBuilder(
            index, org.jcjxb.wsn.service.proto.BasicDataType.Event.getDefaultInstance());
      }
      public java.util.List<org.jcjxb.wsn.service.proto.BasicDataType.Event.Builder> 
           getEventBuilderList() {
        return getEventFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          org.jcjxb.wsn.service.proto.BasicDataType.Event, org.jcjxb.wsn.service.proto.BasicDataType.Event.Builder, org.jcjxb.wsn.service.proto.BasicDataType.EventOrBuilder> 
          getEventFieldBuilder() {
        if (eventBuilder_ == null) {
          eventBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              org.jcjxb.wsn.service.proto.BasicDataType.Event, org.jcjxb.wsn.service.proto.BasicDataType.Event.Builder, org.jcjxb.wsn.service.proto.BasicDataType.EventOrBuilder>(
                  event_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          event_ = null;
        }
        return eventBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:org.jcjxb.wsn.service.EventsRequest)
    }
    
    static {
      defaultInstance = new EventsRequest(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:org.jcjxb.wsn.service.EventsRequest)
  }
  
  public static abstract class SService
      implements com.google.protobuf.Service {
    protected SService() {}
    
    public interface Interface {
      public abstract void startSimulation(
          com.google.protobuf.RpcController controller,
          org.jcjxb.wsn.service.proto.WSNConfig.SimulationConfig request,
          com.google.protobuf.RpcCallback<org.jcjxb.wsn.service.proto.BasicDataType.Empty> done);
      
      public abstract void exec(
          com.google.protobuf.RpcController controller,
          org.jcjxb.wsn.service.proto.SlaveService.ExecRequest request,
          com.google.protobuf.RpcCallback<org.jcjxb.wsn.service.proto.SlaveService.LVTSync> done);
      
      public abstract void sendEvents(
          com.google.protobuf.RpcController controller,
          org.jcjxb.wsn.service.proto.SlaveService.EventsRequest request,
          com.google.protobuf.RpcCallback<org.jcjxb.wsn.service.proto.BasicDataType.Empty> done);
      
      public abstract void endSimulation(
          com.google.protobuf.RpcController controller,
          org.jcjxb.wsn.service.proto.BasicDataType.Empty request,
          com.google.protobuf.RpcCallback<org.jcjxb.wsn.service.proto.BasicDataType.Empty> done);
      
    }
    
    public static com.google.protobuf.Service newReflectiveService(
        final Interface impl) {
      return new SService() {
        @java.lang.Override
        public  void startSimulation(
            com.google.protobuf.RpcController controller,
            org.jcjxb.wsn.service.proto.WSNConfig.SimulationConfig request,
            com.google.protobuf.RpcCallback<org.jcjxb.wsn.service.proto.BasicDataType.Empty> done) {
          impl.startSimulation(controller, request, done);
        }
        
        @java.lang.Override
        public  void exec(
            com.google.protobuf.RpcController controller,
            org.jcjxb.wsn.service.proto.SlaveService.ExecRequest request,
            com.google.protobuf.RpcCallback<org.jcjxb.wsn.service.proto.SlaveService.LVTSync> done) {
          impl.exec(controller, request, done);
        }
        
        @java.lang.Override
        public  void sendEvents(
            com.google.protobuf.RpcController controller,
            org.jcjxb.wsn.service.proto.SlaveService.EventsRequest request,
            com.google.protobuf.RpcCallback<org.jcjxb.wsn.service.proto.BasicDataType.Empty> done) {
          impl.sendEvents(controller, request, done);
        }
        
        @java.lang.Override
        public  void endSimulation(
            com.google.protobuf.RpcController controller,
            org.jcjxb.wsn.service.proto.BasicDataType.Empty request,
            com.google.protobuf.RpcCallback<org.jcjxb.wsn.service.proto.BasicDataType.Empty> done) {
          impl.endSimulation(controller, request, done);
        }
        
      };
    }
    
    public static com.google.protobuf.BlockingService
        newReflectiveBlockingService(final BlockingInterface impl) {
      return new com.google.protobuf.BlockingService() {
        public final com.google.protobuf.Descriptors.ServiceDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }
        
        public final com.google.protobuf.Message callBlockingMethod(
            com.google.protobuf.Descriptors.MethodDescriptor method,
            com.google.protobuf.RpcController controller,
            com.google.protobuf.Message request)
            throws com.google.protobuf.ServiceException {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.callBlockingMethod() given method descriptor for " +
              "wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return impl.startSimulation(controller, (org.jcjxb.wsn.service.proto.WSNConfig.SimulationConfig)request);
            case 1:
              return impl.exec(controller, (org.jcjxb.wsn.service.proto.SlaveService.ExecRequest)request);
            case 2:
              return impl.sendEvents(controller, (org.jcjxb.wsn.service.proto.SlaveService.EventsRequest)request);
            case 3:
              return impl.endSimulation(controller, (org.jcjxb.wsn.service.proto.BasicDataType.Empty)request);
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }
        
        public final com.google.protobuf.Message
            getRequestPrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getRequestPrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return org.jcjxb.wsn.service.proto.WSNConfig.SimulationConfig.getDefaultInstance();
            case 1:
              return org.jcjxb.wsn.service.proto.SlaveService.ExecRequest.getDefaultInstance();
            case 2:
              return org.jcjxb.wsn.service.proto.SlaveService.EventsRequest.getDefaultInstance();
            case 3:
              return org.jcjxb.wsn.service.proto.BasicDataType.Empty.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }
        
        public final com.google.protobuf.Message
            getResponsePrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getResponsePrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return org.jcjxb.wsn.service.proto.BasicDataType.Empty.getDefaultInstance();
            case 1:
              return org.jcjxb.wsn.service.proto.SlaveService.LVTSync.getDefaultInstance();
            case 2:
              return org.jcjxb.wsn.service.proto.BasicDataType.Empty.getDefaultInstance();
            case 3:
              return org.jcjxb.wsn.service.proto.BasicDataType.Empty.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }
        
      };
    }
    
    public abstract void startSimulation(
        com.google.protobuf.RpcController controller,
        org.jcjxb.wsn.service.proto.WSNConfig.SimulationConfig request,
        com.google.protobuf.RpcCallback<org.jcjxb.wsn.service.proto.BasicDataType.Empty> done);
    
    public abstract void exec(
        com.google.protobuf.RpcController controller,
        org.jcjxb.wsn.service.proto.SlaveService.ExecRequest request,
        com.google.protobuf.RpcCallback<org.jcjxb.wsn.service.proto.SlaveService.LVTSync> done);
    
    public abstract void sendEvents(
        com.google.protobuf.RpcController controller,
        org.jcjxb.wsn.service.proto.SlaveService.EventsRequest request,
        com.google.protobuf.RpcCallback<org.jcjxb.wsn.service.proto.BasicDataType.Empty> done);
    
    public abstract void endSimulation(
        com.google.protobuf.RpcController controller,
        org.jcjxb.wsn.service.proto.BasicDataType.Empty request,
        com.google.protobuf.RpcCallback<org.jcjxb.wsn.service.proto.BasicDataType.Empty> done);
    
    public static final
        com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptor() {
      return org.jcjxb.wsn.service.proto.SlaveService.getDescriptor().getServices().get(0);
    }
    public final com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    
    public final void callMethod(
        com.google.protobuf.Descriptors.MethodDescriptor method,
        com.google.protobuf.RpcController controller,
        com.google.protobuf.Message request,
        com.google.protobuf.RpcCallback<
          com.google.protobuf.Message> done) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.callMethod() given method descriptor for wrong " +
          "service type.");
      }
      switch(method.getIndex()) {
        case 0:
          this.startSimulation(controller, (org.jcjxb.wsn.service.proto.WSNConfig.SimulationConfig)request,
            com.google.protobuf.RpcUtil.<org.jcjxb.wsn.service.proto.BasicDataType.Empty>specializeCallback(
              done));
          return;
        case 1:
          this.exec(controller, (org.jcjxb.wsn.service.proto.SlaveService.ExecRequest)request,
            com.google.protobuf.RpcUtil.<org.jcjxb.wsn.service.proto.SlaveService.LVTSync>specializeCallback(
              done));
          return;
        case 2:
          this.sendEvents(controller, (org.jcjxb.wsn.service.proto.SlaveService.EventsRequest)request,
            com.google.protobuf.RpcUtil.<org.jcjxb.wsn.service.proto.BasicDataType.Empty>specializeCallback(
              done));
          return;
        case 3:
          this.endSimulation(controller, (org.jcjxb.wsn.service.proto.BasicDataType.Empty)request,
            com.google.protobuf.RpcUtil.<org.jcjxb.wsn.service.proto.BasicDataType.Empty>specializeCallback(
              done));
          return;
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }
    
    public final com.google.protobuf.Message
        getRequestPrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getRequestPrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return org.jcjxb.wsn.service.proto.WSNConfig.SimulationConfig.getDefaultInstance();
        case 1:
          return org.jcjxb.wsn.service.proto.SlaveService.ExecRequest.getDefaultInstance();
        case 2:
          return org.jcjxb.wsn.service.proto.SlaveService.EventsRequest.getDefaultInstance();
        case 3:
          return org.jcjxb.wsn.service.proto.BasicDataType.Empty.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }
    
    public final com.google.protobuf.Message
        getResponsePrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getResponsePrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return org.jcjxb.wsn.service.proto.BasicDataType.Empty.getDefaultInstance();
        case 1:
          return org.jcjxb.wsn.service.proto.SlaveService.LVTSync.getDefaultInstance();
        case 2:
          return org.jcjxb.wsn.service.proto.BasicDataType.Empty.getDefaultInstance();
        case 3:
          return org.jcjxb.wsn.service.proto.BasicDataType.Empty.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }
    
    public static Stub newStub(
        com.google.protobuf.RpcChannel channel) {
      return new Stub(channel);
    }
    
    public static final class Stub extends org.jcjxb.wsn.service.proto.SlaveService.SService implements Interface {
      private Stub(com.google.protobuf.RpcChannel channel) {
        this.channel = channel;
      }
      
      private final com.google.protobuf.RpcChannel channel;
      
      public com.google.protobuf.RpcChannel getChannel() {
        return channel;
      }
      
      public  void startSimulation(
          com.google.protobuf.RpcController controller,
          org.jcjxb.wsn.service.proto.WSNConfig.SimulationConfig request,
          com.google.protobuf.RpcCallback<org.jcjxb.wsn.service.proto.BasicDataType.Empty> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          org.jcjxb.wsn.service.proto.BasicDataType.Empty.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            org.jcjxb.wsn.service.proto.BasicDataType.Empty.class,
            org.jcjxb.wsn.service.proto.BasicDataType.Empty.getDefaultInstance()));
      }
      
      public  void exec(
          com.google.protobuf.RpcController controller,
          org.jcjxb.wsn.service.proto.SlaveService.ExecRequest request,
          com.google.protobuf.RpcCallback<org.jcjxb.wsn.service.proto.SlaveService.LVTSync> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(1),
          controller,
          request,
          org.jcjxb.wsn.service.proto.SlaveService.LVTSync.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            org.jcjxb.wsn.service.proto.SlaveService.LVTSync.class,
            org.jcjxb.wsn.service.proto.SlaveService.LVTSync.getDefaultInstance()));
      }
      
      public  void sendEvents(
          com.google.protobuf.RpcController controller,
          org.jcjxb.wsn.service.proto.SlaveService.EventsRequest request,
          com.google.protobuf.RpcCallback<org.jcjxb.wsn.service.proto.BasicDataType.Empty> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(2),
          controller,
          request,
          org.jcjxb.wsn.service.proto.BasicDataType.Empty.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            org.jcjxb.wsn.service.proto.BasicDataType.Empty.class,
            org.jcjxb.wsn.service.proto.BasicDataType.Empty.getDefaultInstance()));
      }
      
      public  void endSimulation(
          com.google.protobuf.RpcController controller,
          org.jcjxb.wsn.service.proto.BasicDataType.Empty request,
          com.google.protobuf.RpcCallback<org.jcjxb.wsn.service.proto.BasicDataType.Empty> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(3),
          controller,
          request,
          org.jcjxb.wsn.service.proto.BasicDataType.Empty.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            org.jcjxb.wsn.service.proto.BasicDataType.Empty.class,
            org.jcjxb.wsn.service.proto.BasicDataType.Empty.getDefaultInstance()));
      }
    }
    
    public static BlockingInterface newBlockingStub(
        com.google.protobuf.BlockingRpcChannel channel) {
      return new BlockingStub(channel);
    }
    
    public interface BlockingInterface {
      public org.jcjxb.wsn.service.proto.BasicDataType.Empty startSimulation(
          com.google.protobuf.RpcController controller,
          org.jcjxb.wsn.service.proto.WSNConfig.SimulationConfig request)
          throws com.google.protobuf.ServiceException;
      
      public org.jcjxb.wsn.service.proto.SlaveService.LVTSync exec(
          com.google.protobuf.RpcController controller,
          org.jcjxb.wsn.service.proto.SlaveService.ExecRequest request)
          throws com.google.protobuf.ServiceException;
      
      public org.jcjxb.wsn.service.proto.BasicDataType.Empty sendEvents(
          com.google.protobuf.RpcController controller,
          org.jcjxb.wsn.service.proto.SlaveService.EventsRequest request)
          throws com.google.protobuf.ServiceException;
      
      public org.jcjxb.wsn.service.proto.BasicDataType.Empty endSimulation(
          com.google.protobuf.RpcController controller,
          org.jcjxb.wsn.service.proto.BasicDataType.Empty request)
          throws com.google.protobuf.ServiceException;
    }
    
    private static final class BlockingStub implements BlockingInterface {
      private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
        this.channel = channel;
      }
      
      private final com.google.protobuf.BlockingRpcChannel channel;
      
      public org.jcjxb.wsn.service.proto.BasicDataType.Empty startSimulation(
          com.google.protobuf.RpcController controller,
          org.jcjxb.wsn.service.proto.WSNConfig.SimulationConfig request)
          throws com.google.protobuf.ServiceException {
        return (org.jcjxb.wsn.service.proto.BasicDataType.Empty) channel.callBlockingMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          org.jcjxb.wsn.service.proto.BasicDataType.Empty.getDefaultInstance());
      }
      
      
      public org.jcjxb.wsn.service.proto.SlaveService.LVTSync exec(
          com.google.protobuf.RpcController controller,
          org.jcjxb.wsn.service.proto.SlaveService.ExecRequest request)
          throws com.google.protobuf.ServiceException {
        return (org.jcjxb.wsn.service.proto.SlaveService.LVTSync) channel.callBlockingMethod(
          getDescriptor().getMethods().get(1),
          controller,
          request,
          org.jcjxb.wsn.service.proto.SlaveService.LVTSync.getDefaultInstance());
      }
      
      
      public org.jcjxb.wsn.service.proto.BasicDataType.Empty sendEvents(
          com.google.protobuf.RpcController controller,
          org.jcjxb.wsn.service.proto.SlaveService.EventsRequest request)
          throws com.google.protobuf.ServiceException {
        return (org.jcjxb.wsn.service.proto.BasicDataType.Empty) channel.callBlockingMethod(
          getDescriptor().getMethods().get(2),
          controller,
          request,
          org.jcjxb.wsn.service.proto.BasicDataType.Empty.getDefaultInstance());
      }
      
      
      public org.jcjxb.wsn.service.proto.BasicDataType.Empty endSimulation(
          com.google.protobuf.RpcController controller,
          org.jcjxb.wsn.service.proto.BasicDataType.Empty request)
          throws com.google.protobuf.ServiceException {
        return (org.jcjxb.wsn.service.proto.BasicDataType.Empty) channel.callBlockingMethod(
          getDescriptor().getMethods().get(3),
          controller,
          request,
          org.jcjxb.wsn.service.proto.BasicDataType.Empty.getDefaultInstance());
      }
      
    }
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_jcjxb_wsn_service_ExecRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_jcjxb_wsn_service_ExecRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_jcjxb_wsn_service_LVTSync_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_jcjxb_wsn_service_LVTSync_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_jcjxb_wsn_service_LVTSync_Update_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_jcjxb_wsn_service_LVTSync_Update_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_jcjxb_wsn_service_EventsRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_jcjxb_wsn_service_EventsRequest_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022SlaveService.proto\022\025org.jcjxb.wsn.serv" +
      "ice\032\023BasicDataType.proto\032\017WSNConfig.prot" +
      "o\"(\n\013ExecRequest\022\031\n\021globalVirtualTime\030\001 " +
      "\001(\003\"\222\001\n\007LVTSync\022\017\n\007slaveId\030\001 \001(\005\022\021\n\tloca" +
      "lTime\030\002 \001(\003\0225\n\006update\030\003 \003(\0132%.org.jcjxb." +
      "wsn.service.LVTSync.Update\032,\n\006Update\022\017\n\007" +
      "slaveId\030\001 \001(\005\022\021\n\tlocalTime\030\002 \001(\003\"<\n\rEven" +
      "tsRequest\022+\n\005event\030\001 \003(\0132\034.org.jcjxb.wsn" +
      ".service.Event2\317\002\n\010SService\022X\n\017startSimu" +
      "lation\022\'.org.jcjxb.wsn.service.Simulatio",
      "nConfig\032\034.org.jcjxb.wsn.service.Empty\022J\n" +
      "\004exec\022\".org.jcjxb.wsn.service.ExecReques" +
      "t\032\036.org.jcjxb.wsn.service.LVTSync\022P\n\nsen" +
      "dEvents\022$.org.jcjxb.wsn.service.EventsRe" +
      "quest\032\034.org.jcjxb.wsn.service.Empty\022K\n\re" +
      "ndSimulation\022\034.org.jcjxb.wsn.service.Emp" +
      "ty\032\034.org.jcjxb.wsn.service.EmptyB.\n\033org." +
      "jcjxb.wsn.service.protoB\014SlaveService\210\001\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_org_jcjxb_wsn_service_ExecRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_org_jcjxb_wsn_service_ExecRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_jcjxb_wsn_service_ExecRequest_descriptor,
              new java.lang.String[] { "GlobalVirtualTime", },
              org.jcjxb.wsn.service.proto.SlaveService.ExecRequest.class,
              org.jcjxb.wsn.service.proto.SlaveService.ExecRequest.Builder.class);
          internal_static_org_jcjxb_wsn_service_LVTSync_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_org_jcjxb_wsn_service_LVTSync_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_jcjxb_wsn_service_LVTSync_descriptor,
              new java.lang.String[] { "SlaveId", "LocalTime", "Update", },
              org.jcjxb.wsn.service.proto.SlaveService.LVTSync.class,
              org.jcjxb.wsn.service.proto.SlaveService.LVTSync.Builder.class);
          internal_static_org_jcjxb_wsn_service_LVTSync_Update_descriptor =
            internal_static_org_jcjxb_wsn_service_LVTSync_descriptor.getNestedTypes().get(0);
          internal_static_org_jcjxb_wsn_service_LVTSync_Update_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_jcjxb_wsn_service_LVTSync_Update_descriptor,
              new java.lang.String[] { "SlaveId", "LocalTime", },
              org.jcjxb.wsn.service.proto.SlaveService.LVTSync.Update.class,
              org.jcjxb.wsn.service.proto.SlaveService.LVTSync.Update.Builder.class);
          internal_static_org_jcjxb_wsn_service_EventsRequest_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_org_jcjxb_wsn_service_EventsRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_jcjxb_wsn_service_EventsRequest_descriptor,
              new java.lang.String[] { "Event", },
              org.jcjxb.wsn.service.proto.SlaveService.EventsRequest.class,
              org.jcjxb.wsn.service.proto.SlaveService.EventsRequest.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.jcjxb.wsn.service.proto.BasicDataType.getDescriptor(),
          org.jcjxb.wsn.service.proto.WSNConfig.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
